nextcord/nextcord

README.rst

Made "Fork Notice" text more detailed

---

docs/api.rst
docs/ext/commands/api.rst
docs/ext/commands/cogs.rst
docs/ext/commands/commands.rst
docs/ext/commands/extensions.rst
docs/faq.rst
docs/intents.rst
docs/intro.rst
docs/migrating.rst
docs/migrating_to_async.rst
docs/quickstart.rst
docs/whats_new.rst

Adapting namechange for docs

---

README.rst
docs/intro.rst
examples/background_task.py
examples/background_task_asyncio.py
examples/basic_bot.py
examples/basic_voice.py
examples/converters.py
examples/custom_context.py
examples/deleted.py
examples/edits.py
examples/guessing_game.py
examples/new_member.py
examples/reaction_roles.py
examples/reply.py
examples/secret.py
examples/views/confirm.py
examples/views/counter.py
examples/views/dropdown.py
examples/views/ephemeral.py
examples/views/link.py
examples/views/persistent.py
examples/views/tic_tac_toe.py

"Modernize" examples. 
Previous Pull-Request (#33)
- Unified example class and instance names
- Use nextcord.ext instead of on_message for command handling
- Set prefix to the same in every example

Fix examples

---

nextcord/object.py

castings all discord objects to int gives their discord ID

object int converter

---

examples/secure_token_storage.py

Add [secure_token_storage.py](https://discord.com/channels/881118111967883295/881315976052879451/881324925347061770)

- Add example for secure token storage

---

discord/ext/commands/__init__.py
nextcord/ext/commands/bot.py
nextcord/ext/commands/core.py
nextcord/ext/commands/help.py

Fix pr reviews for #50 

---

discord/ext/commands/__init__.py
nextcord/ext/commands/bot.py
nextcord/ext/commands/core.py
nextcord/ext/commands/help.py

This PR fixes the issue fith aliasing discord.

fix: discord alias

---

.gitignore
discord/__init__.py

and duplicate dunder's
SHould close #65 
add title, author, license, copright, version and path dunder's to discord/init.py
, should fix jishaku and such

attempt to fix imports by moving to 1 wildcard

---

docs/conf.py
docs/index.rst
docs/migrating_2.rst
docs/migrating_to_nextcord.rst
docs/whats_new.rst

Add docfiles

---

discord/abc.py
discord/cooldowns.py
discord/http.py
discord/state.py
discord/utils.py

More import compat

---

.readthedocs.yml

Reference: https://docs.readthedocs.io/en/stable/config-file/v2.html#python-version

RTD docs require python version to be a string

---

docs/migrating_2.rst

adds breaking changes to the migrating to 2.0 docs

added all breaking changes from the gist

---

docs/api.rst

#87 was merged too soon, as jgayfer pointed out, I mistakenly forgot to replace the colons in api.rst

Fixed missing colons

---

README.rst

add info about orjson, aiodns, cchardet, Brotli
ref: https://github.com/nextcord/nextcord/pull/78

add docs for optional packages

---

nextcord/__init__.py
nextcord/health_check.py

This checks that everything in the library is as it should

Feat: Healthcheck

---

docs/migrating_to_nextcord.rst

This PR updates the `migrating_to_nextcord.rst` file to include information on how to port an existing bot from discord.py to nextcord.

Update migration to nextcord docs to include porting from discord.py

---

docs/migrating_to_nextcord.rst

closes #139 (list indentation)

Fx: indent list

---

docs/migrating_2.rst

The python version change was mentioned multiple times
#36

Removing duplicate version notice in migrating_2.rst

---

aliasgen.py

- flaking the file
- Adding support for e.g. Windows Filesystems using \ instead of /
**This is not towards the main branch!**

Making aliasgen.py PEP8 conform and adding support for other filesystems

---

README.rst

Adds a download embed to the readme

Add download embed to readme

---

examples/secure_token_storage.py

Just connecting the example to nextcord.

Example updates.

---

examples/secure_token_storage.py

Typo fix and small addition in the comments

---

discord/__init__.py
nextcord/__init__.py

bumping version for poor mobile epic
code being slow, bumped version for poor epic

bumping ``__version__``

---

docs/intro.rst

This pull request fix the code snippet on [Introduction](https://nextcord.readthedocs.io/en/latest/intro.html#basic-concepts).

Fix code snippet on introduction

---

nextcord/member.py

https://canary.discord.com/channels/881118111967883295/891772093551751229/891772393645805579
pycharm screams when disconnecting someone

move_to optional channel arg

---

docs/_templates/layout.html
docs/index.rst

Changes option discord from `View Documentation For` 

---

nextcord/ui/item.py

Fixed a typo in ui docs

---

nextcord/guild.py

Fixes #165 create_sticker

---

README.rst

Make Discord Server Info Better An Higher Quality With Shields.io

Make Discord Server Info Better An Higher Quality With Shields.io

---

README.rst

Bump Python Version(README)

---

README.rst

Changed Capitalization to be better

Changed Capitalization to be better(On README)

---

.github/workflows/format.yml

Successor To #261 
Per-Commit Linting

Formatting per-commit ci/cd

---

examples/webhook.py

Add webhook example

---

docs/api.rst

fix: use correct types for channel events

---

nextcord/__init__.py

feat: bump to a4

---

nextcord/member.py
nextcord/permissions.py
nextcord/types/member.py

Add timeouts to permissions, edit() and a property

Timeout permission, modify and property

---

docs/api.rst
nextcord/__init__.py
nextcord/application_command.py
nextcord/client.py
nextcord/enums.py
nextcord/errors.py
nextcord/ext/commands/bot.py
nextcord/ext/commands/cog.py
nextcord/ext/commands/core.py
nextcord/guild.py
nextcord/interactions.py
nextcord/state.py

feat: add application command support

Application Command Support

---

examples/application_commands/slash_basic.py

Adds a new example of how to create basic slash commands.

Added basic slash example

---

nextcord/interactions.py

didnt know followup existed :/

fix(inter): send falls back to followup not channel

---

nextcord/guild.py

Documenting that guild.chunk returns a list of members

---

docs/api.rst
nextcord/enums.py
nextcord/flags.py

This PR adds the user flag `known_spammer`

feat: added spammer public user flag

---

nextcord/asset.py

This PR adds support for animated guild banners.

Add support for animated guild banners

---

nextcord/__init__.py

chore: bump version

---

nextcord/guild.py

Urgent fix to resolve import syntax errors

fix: use correct import syntax

---

nextcord/http.py

chore: update api version to v9

---

nextcord/scheduled_events.py

use user_id if member intents is disabled
fixes #345 
- [na] I have updated the documentation to reflect the changes.

fix(events): member intents can work off now?

---

nextcord/application_command.py

This PR constructs a `Member` instance and returns it if all the required data is available for `ApplicationCommandOptionType.user`
This was tested by me.

[Slash Commands] Construct a Member if data is available

---

nextcord/ext/commands/core.py

https://cdn.tooty.xyz/31E5 does not show as an attr properly

fix(ext-core): i dont think numpy defaults as such

---

nextcord/interactions.py

Resolves #330 
Adds `delete_after` as a parameter to `InteractionResponse.send_message`, `InteractionResponse.edit_message`, and `InteractionMessage.edit`.
This makes its behavior more similar to that of sending and editing regular messages. 
Code for testing:
```py
async def delete_after(interaction: Interaction):
await interaction.response.send_message(
"Output from the first example slash command!",
delete_after=2,
)
class EditAndDelete(nextcord.ui.View):
@nextcord.ui.button(label="Delete", style=nextcord.ButtonStyle.red)
async def delete(self, button: nextcord.ui.Button, interaction: nextcord.Interaction):
button.label = "Deleting..."
button.style = nextcord.ButtonStyle.primary
await interaction.response.edit_message(view=self, …
```

feat: Add delete_after to send_message, edit_message, edit

---

nextcord/interactions.py

Moves the delay code from `InteractionMessage.delete` to `Interaction.delete_original_message`. `InteractionMessage.delete` can still take a delay.
This reduces API calls for `InteractionResponse.send_message`, `InteractionResponse.edit_message` when using `delete_after`
`delay` was added to delete_original_interaction so that the message does not need to be fetched first.

perf: Reduce API calls for delete_after

---

docs/api.rst
nextcord/enums.py
nextcord/scheduled_events.py

Document allowed edits for the event status

chore: add note to ScheduledEvent.edit status parameter

---

nextcord/message.py

fixes #361
Change message.thread to a property and get it from the guild cache.
Additionally, construct a thread if it isn't already in the cache.

fix: ensure that a message's thread is the same one in the cache

---

.github/unaliased_health_check.py
.github/workflows/publish.yml

health check still present in unaliased

---

docs/migrating_2.rst
nextcord/enums.py

Add CONTEXT_MENU_COMMAND message type

---

examples/application_commands/autocompleted_command.py
examples/application_commands/choices.py
examples/application_commands/cog_example.py
examples/application_commands/context_menus.py
examples/application_commands/slash_command.py
examples/application_commands/sub_commands.py

Cleans up the formatting on some of the new examples and adds additional sample slash commands to show the usage of `required=False`, `ephemeral` responses, and subcommand groups.
Having `...` in guild ids may be confusing to some users so I changed those to have a testing guild id like the previous slash examples.
A lot of the comments were not helpful (ex. `name="dog", # the name`). I have removed a lot of these to make it easier to read the code.

Refactor and simplify app command examples

---

nextcord/interactions.py

`InteractionResponse.send_message` and `Interaction.send` have `file`/`files` parameters but `InteractionResponse.edit_message` was missed. This adds support to use file kwargs in `edit_message`. 
Code for testing:
```py
class EditWithFile(nextcord.ui.View):
@nextcord.ui.button(label="Show file", style=nextcord.ButtonStyle.success)
async def show(self, button: nextcord.ui.Button, interaction: nextcord.Interaction):
button.label = "File is shown"
button.style = nextcord.ButtonStyle.primary
await interaction.response.edit_message(
view=self, file=nextcord.File("nextcord-logo.png")
)
async def edit_with_file(interaction: Interaction):
await interaction.send("Press to see the file!", view=EditWithFile())
```

feat: Add file/files to InteractionResponse.edit_message

---

nextcord/asset.py
nextcord/guild.py
nextcord/scheduled_events.py
nextcord/types/scheduled_events.py

This implements scheduled events covers and fixes a bug in fetch_scheduled_event.
Docs are found at https://github.com/Aiko-IT-Systems/Discord-API-Docs/pull/13

Implement scheduled event covers

---

nextcord/asset.py
nextcord/guild.py
nextcord/scheduled_events.py
nextcord/types/scheduled_events.py

Revert "Implement scheduled event covers"

---

nextcord/asset.py
nextcord/guild.py
nextcord/scheduled_events.py
nextcord/types/scheduled_events.py

Revert "Revert "Implement scheduled event covers""

---

nextcord/client.py

Stops this log from cluttering logging set to the INFO level

fix(client): improper logging level for event

---

docs/migrating_2.rst
nextcord/application_command.py

Fixed issue #419 and #417

---

docs/migrating_2.rst
nextcord/application_command.py
nextcord/client.py

Fixed more doc typos

---

nextcord/message.py

fix(message): dont assign to the thread property

---

nextcord/application_command.py

Fixes #328, creating an ApplicationCommand from a callback now properly converts string annotations into the correct objects.

`from __future__ import annotations` Slash fix.

---

nextcord/enums.py
nextcord/message.py

fix: is_system()

---

nextcord/gateway.py
nextcord/http.py

Bumps the api version
Please note: This is **not** to the master branch. THe necessary changes for this to work properly will be added to the branch and will not be added in this pr

Bump API Version to v10

---

nextcord/message.py

Please note: Timing this code shows an improvement for dm messages / group messages. Doing the check before the expect however would lead to a significant performance hit for server messages. 
Code has been timed using cProfile

Small performanceimprovement for dm messages

---

discord/__init__.py
nextcord/__init__.py

This changes __title__ to nextcord, this can be used to differentiate forks easily

Change __title__ to nextcord

---

nextcord/ext/tasks/__init__.py

Removes unnecessary cast which wasnt important and errored
refactored to use utcnow instead of datetime.datetime.now(datetime.timezone.utc)
See https://discord.com/channels/881118111967883295/881124672056467456/943262204248072274
Reported by @Shadowaves

Task bugfix and refactoring

---

nextcord/interactions.py

Without this change, it seems to be impossible to replace attachments in API v9.
This should not throw a `TypeError` since the way to replace attachments instead of appending is by passing `attachments=[]`.
Example to replace attachments:
```py
class ReplaceAttachment(nextcord.ui.View):
@nextcord.ui.button(label="Replace Attachment", style=nextcord.ButtonStyle.green)
async def replace(self, _, interaction: nextcord.Interaction):
await interaction.response.edit_message(
file=nextcord.File("logs.txt"),
attachments=[],
)
@client.command()
async def replace_attachment(ctx):
await ctx.send(
"Press to replace attachment!",
view=ReplaceAttachment(),
file=nextcord.File("nextcord-logo.png"),
)
```
Example to append attachments (in v9):
```py
class AppendAttachment(nextcord.ui.View): …
```

fix: replacing attachments

---

nextcord/channel.py
nextcord/message.py

fix subscription is so so so so low

---

nextcord/channel.py
nextcord/message.py

This reverts commit 22402fbc2a9dc836f82d0e801356b13e495fa1b1.

Revert "fix subscription is so so so so low (#471)"

---

docs/migrating_2.rst

i did migrate the webhook part to nextcord instead of dpy 2.0

migrate docs to nextcord

---

nextcord/role.py

icon parameter docs is missing

---

nextcord/interactions.py
nextcord/webhook/async_.py
nextcord/webhook/sync.py

Add attachments to `Interaction.edit_original_message`, `Interaction.edit`, `Webhook.edit_message`, `WebhookMessage.edit`
This allows selecting which attachments to keep in the message and also allows removing existing attachments by passing `[]`.
Resolves #506 
```py
@client.slash_command(guild_ids=[TEST_GUILD_ID])
async def replace_original_attachment(interaction: Interaction):
await interaction.send(
"This is a message with an attachment!",
file=nextcord.File("nextcord-logo.png"),
)
await interaction.edit_original_message(
file=nextcord.File("logs.txt"), attachments=[]
)
@client.slash_command(guild_ids=[TEST_GUILD_ID])
async def append_original_attachment(interaction: Interaction):
await interaction.send(
"This is a message with an attachment!",
file=nextcord.File("nextcord-logo.png"), …
```

feat: Add attachments to edit_original_message, Interaction.edit, Webhook.edit_message, WebhookMessage.edit

---

examples/application_commands/autocompleted_command.py
examples/application_commands/choices.py
examples/application_commands/context_menus.py
examples/application_commands/slash_command.py
examples/application_commands/sub_commands.py

closes #494 
Change from nextcord.Client to commands.Bot in application commands examples
Yes, it fixes issue #494 
- [ x ] If code changes were made then they have been tested.
- [ x ] This PR fixes an issue.

Change nextcord.Client to commands.Bot in examples : fix issue #494

---

nextcord/ext/commands/bot.py

Reverts nextcord/nextcord#518
See https://github.com/nextcord/nextcord/pull/518#issuecomment-1063164220

Revert ":meth: reload_extension docstring Spelling"

---

examples/new_member.py

Fixes typo in `new_member` example

Fixes typo in `new_member` example

---

README.rst

Due to discord.py no longer being discontinued, I figured we have to update the Fork notice.

Fork Notice

---

docs/api.rst
examples/basic_bot.py
examples/modals/modal.py
examples/modals/persistent.py
examples/views/persistent.py
nextcord/components.py
nextcord/state.py
nextcord/ui/modal.py
nextcord/ui/text_input.py

Some code formatting (removal of whitespace, added newlines)
Additional comments and clarification added to examples
Renamed `inter` to `interaction` in examples for consistency
Removed unused imports
Added documentation for auto_defer parameter
Fixes docs warning about underline too short

Refactor and formatting of recent changes

---

nextcord/client.py
nextcord/guild.py
nextcord/http.py

formatted with darker . :)
as maskduck told me was needed, also properly linted

adds with_counts in fetch_guild

---

nextcord/interactions.py
nextcord/ui/view.py

This pull request adds two new properties to `nextcord.Interaction` and one new helper method. Since the Interaction has an id, I added a simple `created_at` returning a datetime object.
In `nextcord.ui.View` I added a check if the interaction has not expired, so it does not error randomly when auto deferring.

Adding interaction.created_at, expires_at and has_expired

---

nextcord/ext/application_checks/core.py

This PR updates nextcord.ext.application_checks's documentations to be better/get fixed

Update Application Checks Documents

---

aliasgen.py
examples/basic_voice.py
examples/head_or_tails.py
examples/secure_token_storage.py
examples/views/link.py
examples/webhook.py
nextcord/activity.py
nextcord/application_command.py
nextcord/ext/application_checks/core.py
nextcord/ext/commands/core.py

docs: Small grammar fixes

---

docs/interactions.rst

This PR changes the use of `nextcord.Client` with `commands.Bot`.

Changed from nextcord.Client to commands.Bot in documentation (interactions.rst)

---

nextcord/application_command.py

fix a small typo in the application_command.user_command docs

fix application docs typo

---

docs/ext/commands/extensions.rst
docs/faq.rst
nextcord/ext/commands/bot.py

setup to be awaitable, fix issue #468

feat: asynchronousifying setup function in cogs

---

nextcord/health_check.py

this add pycord to the imcompatible list (pycord have discord namespace).

pycord is also incompatible, rip bobdotcom

---

nextcord/ext/commands/bot.py

fix(async-setup): update faq link to new docs url

---

nextcord/client.py

fix(client): add tag-epic to license header

---

nextcord/ext/commands/bot.py

fix(commands.Bot): add tag-epic to the license headers

---

nextcord/member.py

fix(Member): fix typehint

---

nextcord/member.py

fix(Member): add tag-epic to license headers

---

nextcord/embeds.py

feat(Embed): return the new embed at `Embed.clear_fields()`

---

nextcord/ext/commands/bot.py

fix(commands.Bot): fix typo

---

nextcord/guild.py

title, cant guarantee on the lintings through

feat(guild): update `Guild.stickers_limit` to match the default limit of 5

---

nextcord/gateway.py

https://github.com/discord/discord-api-docs/pull/5067

refactor(gateway): remove the `$` prefix

---

.github/workflows/docs.yml

This PR will update the version of docs.yml for actions checkout from v2 to v3 and actions setup python from v2 to v4.

ci(docs): update checkout and setup-python

---

.github/workflows/lint.yml

This updates some of the versions of lint.yml (Github action) to more recent versions as some versions are outdated.

ci(lint): update tool versions

---

.github/workflows/publish.yml

This updates the publish.yml CI with new versions as some used are outdated.

ci(publish): update tool versions

---

nextcord/ui/item.py

Just a one-line addition missing from the docs.

docs: Add missing TextInput to Item docstring

---

nextcord/channel.py

This fixes the Voice Channel doc strings so that the version added information is accurate to when the features were actually added.

docs(channel): fix VoiceChannel docstrings

---

docs/api.rst
nextcord/interactions.py
nextcord/message.py
nextcord/types/interactions.py

nextcord.Message.interaction - Represents a command interaction in a message
If Message contains a command interaction, nexcord.Message.interaction will return:
The command name as ".name" (str)
The command ID (message ID?) as ".id" (int)
The user as ".user" (nextcord.User)
The interaction type as ".type" (nextcord.enums.InteractionType)
This is useful to detect when an application command by another bot is used in a message, and know who used the command

feat(message): add Message.interaction

---

nextcord/flags.py

Adds the application command badge flag
https://github.com/discord/discord-api-docs/pull/5222

feat(flags): add ApplicationFlags.application_command_badge

---

docs/api.rst
nextcord/__init__.py
nextcord/audit_logs.py
nextcord/auto_moderation.py
nextcord/enums.py
nextcord/flags.py
nextcord/guild.py
nextcord/http.py
nextcord/iterators.py
nextcord/state.py
nextcord/types/audit_log.py
nextcord/types/auto_moderation.py
nextcord/types/guild.py

Adds auto moderation support, released in <https://github.com/discord/discord-api-docs/pull/4860>.
discord/discord-api-docs#5212 if merged before this PR, will need to be implemented but I am leaving that until it is documented.

feat: add auto moderation support

---

setup.py

Fixes issue with duplicate search results as in sphinx-doc/sphinx#10227.
Fixes #758.

docs: bump sphinx requirement

---

docs/api.rst
nextcord/enums.py

Adds `ChannelType.guild_directory` as documented in discord/discord-api-docs#4701.
Closes #164.

feat(enums): add ChannelType.guild_directory

---

nextcord/http.py

Minor refactoring of http.py
- Removed unused import
- Use of consistent type annotation style
- Added type hints to Unknown-type lists and dicts
- Explicit None check
- Other changes for consistent code-style

refactor: Minor refactoring of http.py

---

examples/custom_context.py

Fixes the custom context example by passing the defined intents to the bots constructor

docs(examples): fix example not using defined intents

---

docs/api.rst
nextcord/enums.py

This kind of breaking changes is listed in [version_guarantees.rst](./docs/version_guarantees.rst) as it is caused by Discord.

refactor(enums)!: remove TriggerType.harmful_link

---

nextcord/ui/view.py

fix(ui): View.add_item is partially unknown

---

nextcord/guild.py
nextcord/http.py
nextcord/member.py

feat: use delete_message_seconds for Guild/Member.ban

---

nextcord/guild.py

fix(channel): import channel types at runtime

---

nextcord/ext/commands/cog.py

Adds a note to the documentation inline with the internal implementation.

docs(commands): document cog_command_error is for prefix

---

nextcord/abc.py

Adds ForumChannel to the list of GuildChannel's in the description
Closes https://github.com/nextcord/nextcord/issues/845

docs(abc): list ForumChannel as an implementation of GuildChannel

---

nextcord/gateway.py

This PR adds typing to all methods in `gateway.py` as raised in #816.

refactor(gateway): add type annotations

---

.pre-commit-config.yaml
docs/extensions/exception_hierarchy.py
nextcord/application_command.py
nextcord/client.py
nextcord/ext/application_checks/core.py
nextcord/ext/application_checks/errors.py
nextcord/ext/commands/bot.py
nextcord/ext/commands/cog.py
nextcord/ext/commands/context.py
nextcord/gateway.py
nextcord/http.py
nextcord/iterators.py
nextcord/member.py
nextcord/shard.py
nextcord/state.py
nextcord/template.py
nextcord/webhook/sync.py

* Adds autoflake for removing unused imports to [`.pre-commit-config.yaml`](https://github.com/nextcord/nextcord/pull/859/files#diff-63a9c44a44acf85fea213a857769990937107cf072831e1a26808cfde9d096b9)
* refactor: Unused imports removed from 16 files

chore: Add removal of unused imports to pre-commit

---

nextcord/guild.py
nextcord/types/guild.py

This documents the new `DEVELOPER_SUPPORT_SERVER` guild feature. Implements https://github.com/discord/discord-api-docs/pull/5572

docs(guild): add DEVELOPER_SUPPORT_SERVER feature

---

nextcord/abc.py

fix(abc): handle timeouts in GuildChannel.permissions_for

---

docs/api.rst
nextcord/auto_moderation.py
nextcord/enums.py
nextcord/types/auto_moderation.py

feat: mention total limit

---

.github/workflows/lint.yml

this PR remove pre-commit GH actions because there's already the integration applied and the action is deprecated anyway

ci: remove pre-commit

---

docs/api.rst
nextcord/ui/select/channel.py
nextcord/ui/select/mentionable.py
nextcord/ui/select/role.py
nextcord/ui/select/user.py

I forgot to edit the docs of *Select.values in #848 , so I edited it.

docs(ui): fix *SelectValues

---

nextcord/enums.py

~~- [ ] I have updated the documentation to reflect the changes.~~

refactor(enums): use bitshifting for bitwise enums

---

docs/api.rst
nextcord/enums.py

feat(enums): HTTP interaction bot flag

---

nextcord/enums.py

feat(enums): add indonesian locale

---

nextcord/role.py
nextcord/types/role.py

<https://github.com/discord/discord-api-docs/commit/6f18f944b7ccd7b6a8d87b421874badac3850ea8>

feat(role): update tags with recent fields

---

nextcord/components.py
nextcord/ext/commands/core.py
nextcord/ext/tasks/__init__.py
nextcord/ui/modal.py
requirements-dev.txt

Use [Pyright 1.1.290](https://github.com/microsoft/pyright/releases/tag/1.1.290).
This removes some type ignores, gives note to some issues, but there seems to be some regression in pyright.

refactor: use pyright 1.1.190

---

docs/api.rst
nextcord/__init__.py
nextcord/enums.py
nextcord/http.py
nextcord/role_connections.py
nextcord/types/appinfo.py
nextcord/types/role_connections.py

Since the majority of this is via OAuth2, there is little support to provide in nextcord right now.
<https://github.com/discord/discord-api-docs/commit/205ceb49ae80240024b62ebe5cc0ded92b21aaad>

feat: add role connections

---

docs/api.rst
nextcord/enums.py

- Implements discord/discord-api-docs#5833

feat(enums): add StickerFormatType.gif

---

nextcord/flags.py
nextcord/state.py

This PR implements the new `GUILD_AUDIT_LOG_ENTRY_CREATE` event. Closes #973.

feat: add on_guild_audit_log_entry_create event

---

nextcord/abc.py
nextcord/channel.py
nextcord/http.py
nextcord/interactions.py
nextcord/webhook/async_.py

feat(message): send message flag

---

nextcord/application_command.py
nextcord/http.py

refactor: remove mutable parameter defaults

---

nextcord/colour.py

The dark theme colour on the UI recently changed and so therefore this has changed `nextcord.Colour.dark_theme()` to use the new colour.

fix(colour): use new dark theme colour

---

nextcord/ext/commands/core.py

This fixes the following type issues:
```py
Argument of type "(ctx: Context[Unknown]) -> Coroutine[Any, Any, None]" cannot be assigned to parameter of type "((CogT, ContextT@command, **P) -> Coro[T]) | ((ContextT@command, **P) -> Coro[T])"
Type "(ctx: Context[Unknown]) -> Coroutine[Any, Any, None]" cannot be assigned to type "((CogT, ContextT@command, **P) -> Coro[T]) | ((ContextT@command, **P) -> Coro[T])"
Type "(ctx: Context[Unknown]) -> Coroutine[Any, Any, None]" cannot be assigned to type "(CogT, ContextT@command, **P) -> Coro[T]"
Function accepts too many positional parameters; expected 1 but received 2
Parameter 1: type "CogT" cannot be assigned to type "Context[Unknown]"
"Cog*" is incompatible with "Context[Unknown]"
Type "(ctx: Context[Unknown]) -> Coroutine[Any, Any, None]" …
```

typing(commands): resolve issues with command and group types

---

README.rst

Fixes the link to the examples as the stable branch no longer exists.

docs(readme): fix examples links

---

nextcord/application_command.py

This adds a documentation for `SlashCommandMixin.options`.

docs(app-cmds): document SlashCommandMixin.options

---

nextcord/guild.py

`Optinal` --> `Optional`
Fixes a typo in `nextcord/guild.py`.

docs(guild): fix typo of Optional

---

nextcord/flags.py

Implements discord/discord-api-docs#6021
Note that I am unsure if the name of the flag is okay, I've just used what it was called in the documentation.

feat(flags): add ApplicationFlags.application_auto_moderation_rule_create

---

nextcord/guild.py
nextcord/types/guild.py

feat(guild): add premium_progress_bar_enabled

---

docs/api.rst
nextcord/__init__.py
nextcord/client.py
nextcord/emoji.py
nextcord/guild_preview.py
nextcord/http.py
nextcord/state.py
nextcord/types/guild.py

This implements the GuildPreview function, along with some related functions for Client, and HTTPClient.

feat: add guild preview

---

README.rst

This updates the invite to the Discord API guild. It leads to the official API guild now.

docs(README): update Discord API guild invite

---

nextcord/application_command.py
nextcord/scheduled_events.py

The metadata attribute on the data was incorrect, this has been updated in accordance with the correct field name. See discord docs for this [here](https://discord.com/developers/docs/resources/guild-scheduled-event#guild-scheduled-event)
<!--

fix(scheduled-events): event metadata missing

---

nextcord/threads.py

Tags on (forum) threads now correctly update when `THREAD_UPDATE` is dispatched.
Fixes #1097

fix(threads): update applied_tag_ids

---

nextcord/flags.py
nextcord/message.py
nextcord/types/message.py

- Implements discord/discord-api-docs#6272

feat: add attachment flags

---

nextcord/auto_moderation.py
nextcord/guild.py
nextcord/types/auto_moderation.py
nextcord/types/guild.py

- discord/discord-api-docs#5778

feat(auto_moderation): add join and mention raid fields

---

docs/api.rst
nextcord/abc.py
nextcord/channel.py
nextcord/enums.py
nextcord/guild.py
nextcord/message.py
nextcord/types/guild.py

Add the relevant fields and parameters for stage channels
discord/discord-api-docs#5928, discord/discord-api-docs#5927
I have not tested this yet but hopefully will later on.

feat: add text in stage

---

nextcord/guild.py

Update the documentation to reflect https://github.com/discord/discord-api-docs/pull/6685
This is a single-word docs-only change, no code has been updated, so testing/etc have been skipped.

docs: update required permissions for prune

---

nextcord/interactions.py

Supersedes #1182
Still fixes #1168
-  ~~I have updated the documentation to reflect the changes.~~

refactor: remove _InteractionMessageState hack

---

nextcord/channel.py

Adds .webhooks to ForumChannels, StageChannels, and VoiceChannels.
Resolves #1176

feat: add list of webhooks to forum, stage, and voice channels

---

nextcord/player.py

This PR adds some clarifying documentation around the executable parameters of audio classes based off of internal discussions.

doc: add clarification to executable param

---

nextcord/audit_logs.py

docs(audit-logs): document missing attribute

---

docs/api.rst
nextcord/abc.py
nextcord/enums.py
nextcord/message.py
nextcord/types/message.py

- Implements discord/discord-api-docs#6833
- Closes #1214
Tested with: https://paste.nextcord.dev/?id=1728150917630869 & https://paste.nextcord.dev/?id=1729079833667392

feat: add message snapshots/forwarding

---

nextcord/client.py

Calling asyncio.get_event_loop() emits a deprecation warning as of Python 3.12; in a future release, the method will be deprecated entirely, instead throwing an error. The preferred means of getting the current event loop is to call asyncio.get_running_loop(); in the event that doing so throws a RuntimeError, directly create a new event loop instead. After obtaining the loop, set it.
I confirmed that the docs properly update and link to the relevant methods; note that I had to run `pip install --upgrade sphinx` in order to do so, as with the version installed through pyproject.toml, I got the following error:
`Could not import extension sphinx.builders.epub3 (exception: No module named 'imghdr')`. I will be opening an issue for this shortly.
Console output from running my bot with this …

refactor(client): future-proof event loop handling with get_event_loop

---

nextcord/permissions.py

Added the existing new permissions since 2.0 to the relevant classmethods. These long binary strings are not very readable,
so need some sort of more human readable representation.

feat(permissions): update Permission classmethods

---

.github/workflows/docs.yml
.github/workflows/lint.yml
.github/workflows/publish.yml
.readthedocs.yml
README.rst
docs/extensions/builder.py
docs/intro.rst
nextcord/role.py
nextcord/state.py
nextcord/utils.py
pyproject.toml

Resolves #1205. This does not remove deprecated code or code that can be upgraded. This can be done in separate PRs, this is the minimum work to create this breaking change for 3.0 so 3.12 remains as the minimum version for the future.
<!--

build: set minimum python version to 3.12

---

nextcord/client.py
nextcord/emoji.py
nextcord/http.py
nextcord/types/emoji.py

This PR adds support for application emojis.
Relevant links:
- https://discord.com/developers/docs/change-log#application-emoji
- https://github.com/discord/discord-api-docs/pull/7010

feat: application emojis
