nextcord/nextcord

README.rst

The discord.py library is a singular noun, so the has verb must be has

changed have been to has been

---

README.rst
discord/__init__.py
discord/ext/commands/__init__.py
discord/ext/tasks/__init__.py
discord/opus.py
discord/types/__init__.py
discord/ui/__init__.py
discord/voice_client.py
discord/webhook/__init__.py

Changes the wording of the README and the `discord/**/__init__.py` docstrings to be more exact.

docs: change wording of readme and docstrings

---

README.rst

I always found the docs link too far down in the discord.py repo that it takes too long to find.
This change adds an additional link to make it easier for newcomers to find the docs.
I also added a header to create extra padding above the first paragraph.
:one: is the current readme
:two: is with the [updated readme](https://github.com/DenverCoderOne/nextcord/blob/enhanced-readme/README.rst)

Added docs link at the top

---

README.rst
docs/api.rst
docs/discord.rst
docs/faq.rst
docs/index.rst
docs/intents.rst
docs/intro.rst
docs/migrating.rst
docs/migrating_2.rst
docs/migrating_to_async.rst
docs/migrating_to_nextcord.rst
docs/quickstart.rst
docs/version_guarantees.rst
docs/whats_new.rst

Fixed 50+ spelling and grammar mistakes in the readme and documentation.

Fixed typos in docs

---

docs/migrating_2.rst

This pull requests removes the confusing brackets system for the migrating guide and instead just puts everything into two sections - `Changes` and `Removals`. An `Additions` section will be added eventually detailing the new interactions support.
If a dev wants to find something specific within the guide, they can just use the sidebar to find it quickly.

Refactor migrating docs to make them clearer.

---

docs/api.rst
nextcord/raw_models.py
nextcord/state.py
nextcord/types/raw_models.py

Adds in an `on_raw_typing` event. This may be useful if the typing starts in a DM, as otherwise, d.py is unable to resolve the user and so unable to dispatch an `on_typing` event.
Note that even with #145, this event is still useful in case the typing itself comes from a user that comes outside of the bot's user cache, a likely possibility if `Intents.members` is disabled. In fact, this PR was made and adjusted with #145 in mind, at least in terms of the documentation's wording (there might be merge conflicts between this PR and that one - sorry!).
Closes #7.

Added `on_raw_typing` event

---

README.rst

Reverts invite link to non-custom url.
Was changed but invite no longer works: https://github.com/nextcord/nextcord/commit/5f195c360f3060938e2445ef0a255956c1271633

docs: Revert custom url

---

docs/logging.rst

Docs specify changing the logging level of the "discord" logger, when it should be "nextcord"

Specifies nextcord logger instead of discord

---

nextcord/asset.py

Restoration of #56, which I accidentally closed because of force-pushing messiness.
Summary of old PR:
> In short: something like `Asset.replace(format='gif',static_format='png')` would break if it encountered a static asset, as static avatars cannot be stored in a GIF format and d.py preferred to use the `format` format vs. the `static_format` format, even with static assets. According to Danny, this was an intentional feature, but I personally do not see how keeping the old behavior would be beneficial to anyone at all.
> Link to issue here: #13
> Link to issue on `discord.py`: [#7345](https://github.com/Rapptz/discord.py/issues/7345)

Prefer `static_format` over `format` with static assets

---

MANIFEST.in

It seems that this was added back at 55f79ed0967eac109b262401f6361e1b292a6b52 but accidentally removed on b644c29841ec878b77b6a38bdb6e754bf7ec90e2 and 4f38c6dd5977c9047f88eb61d644e8f0bb0ea779. The file is required per [PEP 561](https://www.python.org/dev/peps/pep-0561/#toc-entry-5) for type-checkers to not ignore the module's type annotations, so it should be here as the package is type-annotated
Another ref: [mypy's docs](https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages)

fix: missing required `py.typed` for type checkers

---

nextcord/embeds.py

Embed.url was defined as 'The url of the embed', which incorrectly described its usage as to hyperlink the title of the embed.
Fix by changing the description.

Fix embed.url description.

---

docs/ext/commands/api.rst
nextcord/__init__.py
nextcord/ext/commands/bot.py
nextcord/ext/commands/errors.py

It resolves #129 by implementing the ability to have keyword arguments passed through
See the thread under nc-development for testing

Feature: Cog's can now have external config

---

nextcord/ext/commands/core.py

Add's the ability for commands in groups to inherit checks, pre_invoke and after_invoke calls
#123

Feature: Group's hook & check inheritance

---

nextcord/ext/commands/converter.py

MessageConverter and PartialMessageConverter on nextcord.ext.commands.converter should process when user only give MessageID [(according to documentation)](https://nextcord.readthedocs.io/en/latest/ext/commands/api.html#nextcord.ext.commands.MessageConverter)
But actually you get : nextcord.ext.commands.errors.ChannelNotFound: Channel "None" not found.
This PR fix this issue when channel ID not find in User Input by getting Context channel

Fix: MessageConverter error when UserInput only provide MessageID

---

nextcord/interactions.py

this was discussed at https://canary.discord.com/channels/881118111967883295/881124672056467456/903322918413541377
this has been tested by me too
Adds ``interaction.send``, a fallback function for ``interaction.response.send_message`` and ``interaction.channel.send``, useful for everyone: converting and not having to make sure an interaction hasnt been responded to yet like in an interaction_check for a ``View``

Add interaction.send()

---

nextcord/ext/tasks/__init__.py

Makes task.loop check if the time must be on this day or the next
I just noticed this really annoying error after a long debugging session... Should be fixed in order of making time actually usable

Bugfix for task.loop

---

nextcord/role.py

It is Discord UI bug, however this fix works properly on android and win32
When mentioning @everyone role via mention attribute, it has double "@"
Before:
After:

Fix double "@" in Guild.default_role.mention

---

nextcord/permissions.py

This does work, yes, but this should fix an issue with embedded activities and moderate members permissions
Fixes multiple permissions issues with moderate members

`Permissions.all()` uses `-1`

---

nextcord/member.py

`Member.edit`'s timeout kwarg can now take a `datetime.timedelta`

feat(member): allow edit to take a timedelta

---

nextcord/application_command.py
nextcord/client.py
nextcord/ext/commands/bot.py
nextcord/guild.py
nextcord/state.py

SlashOption's choice param now takes an iterable.
rollout_all_guilds kwarg for Client now determines if all Guilds are rollout'd to instead of just the ones specified by the guild_ids param in commands. This is a fix towards the cloudflare ban.
handle_slash_argument is now async, and will auto-fetch user/member if they aren't found in the cache.
Added basic cog reloading support, fix application commands not actually getting removed.
Guild now has its own rollout command.
Adds a fix towards #310, but the only real fix for that is fixing http.
Contains the same exact fix as #313, sorry.
When a member/user can't be gotten from the cache (hi intents!), slash commands will now attempt to fetch it.
Adds a variety of fixes and a few helpers for slash stuff.

Slash fixes

---

nextcord/member.py

Default value for `timeout` parameter is MISSING, but it's checking `if timeout is None`.

Fix: member.edit without a timeout raising an error

---

nextcord/message.py

Parse and use the `thread` field on messages, as documented [here](https://discord.com/developers/docs/resources/channel#message-object).
- If code changes were made then they have been tested.
- I have updated the documentation to reflect the changes.
- This PR adds something new (e.g. new method or parameters).

Feat: Add 'thread' field to messages.

---

nextcord/__init__.py

Bumps the version to 2.0.0a6 for a new PyPI release fixing a bug

chore: bump version to 2.0.0a6

---

nextcord/message.py

Parse and use the `thread` field on message update, not just when creating a new message.
For example, the following code:
```python
import nextcord
client = nextcord.Client(intents=nextcord.Intents.all())
@client.event
async def on_message_edit(before, after):
await after.channel.send(str(after.thread))
client.run("token")
```
Would send `None` in any circumstance before this change, but will send the name of the thread created from the edited message (if any) after this change. This has been tested.

Add handler for message thread field update

---

nextcord/http.py
nextcord/message.py

Adds multiple arguments to the `Message.edit()` function, now allowing to edit files when editing a message.

Add possibility to edit files on a message

---

nextcord/abc.py
nextcord/interactions.py
nextcord/webhook/async_.py

Fixes #353 
Support for attachments in interaction response
Example code used for testing:
```py
async def example1(interaction: Interaction):
await interaction.response.send_message(
"First example slash command!",
embed=nextcord.Embed(
title="Example 1",
description="This is an example of a basic slash command.",
),
file=nextcord.File("nextcord-logo.png"),
)
```
```py
async def example2(interaction: Interaction, arg1: str):
await interaction.response.send_message(
"Second example slash command!",
view=Google(arg1),
files=[
nextcord.File("nextcord-logo.png"),
nextcord.File("nextcord-logo2.png"),
]
)
```

feat: Send files with interaction response

---

docs/api.rst
nextcord/raw_models.py
nextcord/state.py
nextcord/types/raw_models.py

Adds a raw_member_remove event, useful in case the member isn't cached (or chunking is disabled) which makes the client not fire an event at all when a member leaves a guild.

Add raw_member_remove event

---

nextcord/interactions.py

Allows a type 5 defer on component interactions

fix: allow deferring messages on component interactions

---

nextcord/scheduled_events.py

Fixes ScheduledEvent.edit raising an exception because the call to the http function was missing guild_id and event_id parameters.
(Also fixes extra spaces in the file because editor is smart)
- [-] I have updated the documentation to reflect the changes.

fix: ScheduledEvent.edit missing arguments in http

---

nextcord/http.py

You can't edit the status of an event rn because it isn't in the list of valid_keys.
Cough cough kwargs
- [-] I have updated the documentation to reflect the changes.

fix: status not in list of valid_keys for edit event

---

nextcord/state.py

No issue was created since I encountered it, but parameters passed to `on_voice_state_update` are `before` and `after`.
However `after` was a reference to `Member.voice`, which means, when using `Member.move_to()` **inside** `on_voice_state_update` event, `after` would immediately get modified.
Example:
```py
@bot.event
async def on_voice_state_update(member, before, after):
print(after.channel.name)  # prints Channel1
chan = bot.get_channel(1234567890101112)  # Let's say that's "Channel2"
await member.move_to(chan)
print(after.channel.name)  # prints Channel2
```

fix: provide a copy of after in voice_state_update event

---

nextcord/interactions.py

Adds `client` as an attribute of `Interaction`
This functionality is part of the changes in PR #348 but, with permission from @TAG-Epic, I am adding this in its own PR so it can be merged sooner so that https://github.com/nextcord/nextcord-ext-menus/pull/27 can be released.

Add client to interaction class

---

nextcord/interactions.py
nextcord/webhook/async_.py

Adds support for `delete_after` in `WebhookMessage.send`, `WebhookMessage.edit`
Since `interaction.followup` uses `WebhookMessage`, this allows deleting deferred interaction responses.
Similar functionality already exists for regular messages and Interaction messages (#384)
This PR also adds support for `file`, `files` and `delete_after` in `Interaction.send`
Testing code:
```py
async def delete_send(interaction: Interaction):
await interaction.send("This message will be deleted.", delete_after=2)
async def defer_delete_send(interaction: Interaction):
await interaction.response.defer()
await sleep(1)
await interaction.send("This message will be deleted.", delete_after=2) …
```

feat: delete_after for deferred/webhook messages

---

nextcord/state.py

Guild.chunk currently doesn't care about caching
- [-] I have updated the documentation to reflect the changes.

fix: Guild.chunk ignoring cache parameter

---

nextcord/activity.py

Fixes custom activities which can contain no emotes, exception on startup when using nextcord master branch
- [-] I have updated the documentation to reflect the changes.

[URGENT] fix: custom activities can have no emotes AAAA

---

nextcord/application_command.py

Moves docstrings and fixes #397

chore: move docstrings to the correct place

---

nextcord/ext/commands/cooldowns.py

Dynamic cooldowns now work with default bucket types as well.

Fixed dynamic cooldowns (BucketType.default case)

---

nextcord/interactions.py

Adds functionality to use allowed mentions in interaction responses (inital and followup responses).

Add allowed_mentions to interaction responses

---

nextcord/application_command.py

This PR rewrites `_handle_resolved_user` to construct a `Member` is the data if the data available.

[User commands] Construct member if possible

---

docs/ext/commands/api.rst

Fixes error in `make -C docs html`
```
/nextcord/docs/ext/commands/api.rst:646: WARNING: Bullet list ends without a blank line; unexpected unindent.
/nextcord/docs/ext/commands/api.rst:648: ERROR: Unexpected indentation.
```

docs: fix error in bullet list

---

docs/faq.rst

I noticed the doc suggest to use a bare except in the faq. This should not be done for several reasons (e.g. Keyboard Interrupts getting caught) so this would change it

Docs: removed bare except

---

docs/migrating_to_nextcord.rst

For compatibility with the discord alias, I believe it is recommended to uninstall discord.py _before_ installing nextcord.
The migration docs currently have the steps in the other order.

docs: Switch order of installation steps

---

nextcord/application_command.py

When removing an option/parameter, the association checks do not detect a change and will not update Discord with the new command.
This PR makes it so it now checks the length of the options between the local and Discord command.

AppCmd association now checks option length.

---

nextcord/guild.py
nextcord/http.py
nextcord/scheduled_events.py

This PR adds a kwarg called `image` to `Guild.create_scheduled_event()` and `ScheduledEvent.edit()` that allows users to set or remove the event cover image. Fixes #485

Add support for scheduled event cover image

---

nextcord/guild.py

Currently when using ``Guild.fetch_roles``, the updated roles are not cached. This pr adds an additional param to allow for cache updates while defaulting to a backward compat change.

Cache roles within ``Guild.fetch_roles``

---

nextcord/application_command.py

Currently static type checkers will complain that a SlashOption object is not a valid default parameter for a parameter of type `int`, `str`, or anything. E.g.
```py
@nextcord.slash_command(description="bla bla bla")
async def foo(
self,
interaction: nextcord.Interaction,
bar: str = SlashOption(description="bla bla bla"), # SlashOption is not a valid default for parameter of type str
):
pass
```

Make SlashOption extend typing.Any

---

nextcord/ext/commands/bot.py

https://github.com/nextcord/nextcord/edit/master/nextcord/ext/commands/bot.py#L837 
1 word in doc string misspelled 
(from what i see)

:meth: reload_extension docstring Spelling

---

docs/conf.py
docs/migrating_to_async.rst
docs/whats_new.rst
nextcord/ext/commands/help.py
nextcord/member.py
nextcord/object.py

Fixes broken links across documentation that linked to incorrect or non-existent nextcord issues, to direct to their correct destination.
Discord.py issues are now referenced using `:dpyissue:`, new issues and PRs in nextcord can still be referenced using `:issue:`

docs: Fix broken links to dpy issues

---

nextcord/player.py

Sometimes `source.cleanup()` may take several seconds to finish, which causes a noticeable delay when playing audio.
A possible solution is to call `self._call_after()` before `self.source.cleanup()` in `AudioPlayer.run()`.

Fix audio delay when calling after function

---

docs/extensions/attributetable.py
nextcord/ext/commands/cog.py
nextcord/ext/commands/core.py
nextcord/ext/tasks/__init__.py
nextcord/member.py
nextcord/ui/button.py
nextcord/ui/select.py

This PR is supposed to fix some incompatibilities with Cython and Nextcord. 
The first of these is that Cython stores coros internally with the same `co_flags` as a regular function. Since `inspect.iscoroutinefunction` is used a bunch in nextcord to ensure listeners work right, "Pure Python" compiled with Cython cannot use nextcord. Cython *does* add a flag elsewhere that `asyncio.iscoroutinefunction` does check for (see [this](https://github.com/cython/cython/issues/2273#issuecomment-414032693)). I replaced all calls to inspect's impl with asyncio's impl, altering imports where necessary.
This is a draft for now, because I don't want to merge it until I can make a bot using Cython. Once the first obstacle is fixed, I'm sure there will be more.
**I don't know how to test this yet, I was …

Cython compatibility

---

nextcord/ui/view.py

This pull request fixes the `View._expires_at` decor so that it returns the correct timeout.
If you wish to check this yourself
```python
from discord import ui
import asyncio
class MF(ui.View):
@ui.button(label="reset or something")
async def a(self, _, __):
self.first = (self._expires_at, self._View__timeout_expiry)
await asyncio.sleep(2)
self.second = (self._expires_at, self._View__timeout_expiry)
print(self.first, self.second, sep="\n")
await ctx.send("a", view=MF())
```
They *should* be the same values both times, however, they are not. This PR resolves that.
Current output:
```
(34118.328, 34118.328)
(34120.343, 34118.328)
```

fix: Return the correct timeout in _expires_at

---

nextcord/message.py

The `open()` built-in, which `Attachment.save()` calls, can take a str value for its `fp` argument. However 'str' is not covered by the `save()` method's existing type hints. Counter-intuitively, str does not satisfy [`os.PathLike`](https://docs.python.org/3/library/os.html#os.PathLike), as it does not define an `__fspath__` method.
Thus, we extend the type hint by adding "str" to the `Union`. See this example of the same case in python/typeshed: https://github.com/python/typeshed/blob/994b69ef8f18e76689daca3947879c3d7f76173e/stdlib/_typeshed/__init__.pyi#L77

Note that `Attachment.save` can take a `str`-type for `fp`

---

nextcord/member.py
nextcord/utils.py

Just checks if the argument `dt` is an instance of `datetime` to prevent confusion.
Adds a timeout method to member.py as a direct method instead of having to go through `Member.edit`
- [x ] If code changes were made then they have been tested.
- [  ] I have updated the documentation to reflect the changes.
- [  ] This PR fixes an issue.
- [  ] This PR adds something new (e.g. new method or parameters).
- [  ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [  ] This PR is **not** a code change (e.g. documentation, README, ...)

Add check for confirming datetime instance, as well as adding a timeout method to member.py

---

nextcord/utils.py

This pull request aims to make `nextcord.utils.get` aware of the attribute names passed to it.
Prior to this change, `nextcord.utils.get` would blindly replace the `__` delimiter with `.` causing special variables (`__class__`, `__name__`, etc.) to throw an error. I've updated the `str.replace("__", "_")` to use regex to look for edge cases that contain special variables. If the name does not contain special variables, the regular expression will use a lookahead statement for underscores, and greedily replace them with `.`, assuming trailing underscores.
Previous behavior:
```py
>>> fmt("guild__name")
'guild.name'
>>> fmt("trailing___attr")
'trailing._attr'
>>> fmt("__class______name__")
'.class...name.'
```
New behavior:
```py
>>> fmt("guild__name")
'guild.name'
>>> …
```

Make utils.get content-aware

---

docs/api.rst
docs/intents.rst
nextcord/flags.py

Adds MESSAGE_CONTENT intent and GATEWAY_MESSAGE_CONTENT, GATEWAY_MESSAGE_CONTENT_LIMITED application flags.
In v9, these are given by default, but without this change, in v10, the bot will throw an error if Message Content Intent is disabled in the portal.
This fixes intents to work correctly after migrating to v10
References:
- https://github.com/discord/discord-api-docs/blob/77ee0f906a3d9d2aff0bb3c285913e9db25d98dd/docs/resources/Application.md
- https://github.com/discord/discord-api-docs/blob/3891389606ef8710e7c54d65ae79d0c5313f0247/docs/topics/Gateway.md
- https://github.com/discord/discord-api-docs/discussions/4510
- https://support-dev.discord.com/hc/en-us/articles/4404772028055

feat: Add message content intent and additional flags

---

nextcord/file.py
nextcord/http.py
nextcord/interactions.py
nextcord/message.py
nextcord/types/message.py
nextcord/webhook/async_.py
nextcord/webhook/sync.py

Fixes #524 
Adds descriptions to file and attachments.
* `description` attribute added to `nextcord.File`
* `description` attribute added to `nextcord.Attachment`
* `description` field added to `payload['attachments']` where relevant
In order to send files with descriptions, the `payload['attachments']` needs to be set containing the description for each file. Because of this, you can no longer send files without setting `payload['attachments']`. Therefore, the default behavior of editing a message with files is to **REPLACE** the existing attachments rather than **APPEND**.
NOTE: When [API v10 is used](https://github.com/discord/discord-api-docs/discussions/4510), **this will be the default behavior anyway**. Even if `payload['attachments']` is not set, files will be replaced, rather …

feat!: Support for file descriptions

---

nextcord/file.py

Fixes #543 
Previously the attributes documented were mostly information for the constructor parameters but with some errors such as string and bytes types not mentioned.
This PR documents the parameters and attributes more clearly.

docs: Clarifications in File attribute and parameter docs

---

docs/migrating_2.rst
nextcord/appinfo.py

Ref: #467 
https://github.com/discord/discord-api-docs/discussions/4510

docs: warn about AppInfo.summary deprecation

---

nextcord/abc.py
nextcord/http.py
nextcord/message.py

Feature:
* Adds support for sending `embeds` in `PartialMessage.edit`
Fixes:
* Replaces use of deprecated `embed` field in `PartialMessage.edit` with `embeds`
* **Fixes issue when trying to remove content, embeds, or other attributes when editing a message with files**
This PR fixes a bug where if you pass `embed=None` or `embeds=[]` to an edit method while also sending files, the embeds do not get removed.
This bug also applies to sending `view=None`, a view with no components, an empty list of stickers, or empty string as content.
Example:
```py
@bot.command(name="pme")
async def partial_message_embeds(ctx: commands.Context):
pm = ctx.channel.get_partial_message(956263847562477619)
await pm.edit(content="Test 1", embeds=[nextcord.Embed(title="Test"), nextcord.Embed(title="Test 2")]) …
```

Fix issue removing embeds when editing with files and add `embeds` to `PartialMessage.edit`

---

nextcord/ui/modal.py
nextcord/ui/view.py

Adapts expiry changes from views to modals, and auto_defer from modals to views
* Adapts #534 to Modals to not defer if interaction is expired
* Adapts #497 to Modals to fix `Modal._expires_at`
* Adapts `auto_defer` to Views to be consistent with Modals. This allows you to handle component interactions in your command after the callback ends, or handle component interactions in `on_interaction` (see [Help Thread](https://discord.com/channels/881118111967883295/956638253350531092))

fix: Modal _expires_at and View auto_defer

---

nextcord/application_command.py

Allows creating an autocomplete slash command argument using the SlashOption constructor instead of the on_autocomplete decorator.
Thanks @MebinAbraham for coming up with the idea [on Discord](https://discord.com/channels/881118111967883295/955601839150235739).
* Added `autocomplete_function` as an argument to `SlashOption`
* An exception will be raised if you try setting the autocomplete callback using the `on_autocomplete` decorator for an argument that already has an autocomplete callback.
Example usage:
```py
async def favorite_cat(interaction: Interaction, cat: str):
if not cat:
await interaction.response.send_autocomplete(list_of_cat_breeds)
return
get_near_cat = [
breed for breed in list_of_cat_breeds if breed.lower().startswith(cat.lower())
]
await …
```

feat: Add `autocomplete_function` as an argument to `SlashOption`

---

nextcord/interactions.py

* Fix docs for `client` and `bot` in `nextcord.Interaction`
client is documented as a property so should not be in attributes
bot never existed as an attribute so should not be in the documentation
_client does not exist as an attribute so should not be in slots

docs: Remove incorrect attributes from docs

---

docs/migrating_2.rst
nextcord/message.py

* As `context_menu_command` is a system message (just as much as `chat_input_command` is), it should be checked in `is_system()`
* The change from `application_command` to `chat_input_command` does not belong in migrating to 2.0 as it is not a change between 1.7.3 and 2.0 (`application_command` did not exist before 2.0)

fix: Add context_menu_command to is_system

---

docs/interactions.rst

Fixed examples in the Application Commands page of the docs, added examples for normal options, required options, subcommand groups, and defer, updated the wording of the explanations to be more clear and concise, rearranged sections to be in a more logical order.
The diff is pretty big, you can read the new version of the page here:
https://deploy-preview-558--nextcord-gh-action.netlify.app/interactions.html

docs: fix and add examples in application commands page

---

nextcord/utils.py

Supports more types of docstring styles for automatic slash argument descriptions.
* Ensures that descriptions in numpy docstrings have at least one space preceding them
* Adds more non-capturing group markers to places where the groups are unused
This fixes an issue where arguments following a line containing `----------` would not get matched.
Before this change, if using Numpy-style docstrings, you would need a new line or documentation for `interaction` to appear before the first slash argument's documentation, for example:
```py
async def numpy_rst_echo(interaction: Interaction, my_arg: str, my_second_arg: str):
"""NUMPY RST Repeats your messages that you send as arguments
Parameters
----------
interaction: …
```

fix: Support leaving out interaction in numpy docstring

---

docs/api.rst
nextcord/client.py

This adds the "close" event, which can then be listened for by library users to help shutdown parts of their bot, like database connections.
This ended up being a single line addition to the Client.close() function to just dispatch the `close` event but it looks like that's all that should be needed? Would greatly appreciate some feedback or confirmation.

feat: Add close event (#349)

---

nextcord/asset.py

* Adds `to_file` to all objects that use `AssetMixin` (`Asset`, `Emoji`, `PartialEmoji`, `Sticker`)
```py
@bot.command()
async def avatar_file(ctx: commands.Context[commands.Bot]):
file = await ctx.author.display_avatar.to_file()
await ctx.send(file=file)
@bot.command()
async def emoji_file(ctx: commands.Context[commands.Bot], emoji: nextcord.Emoji):
file = await emoji.to_file()
await ctx.send(file=file)
@bot.command()
async def partial_emoji_file(ctx: commands.Context[commands.Bot], partial_emoji: nextcord.PartialEmoji):
file = await partial_emoji.to_file()
await ctx.send(file=file)
@bot.command()
async def sticker_file(ctx: commands.Context[commands.Bot], message_id: int):
msg = await ctx.channel.fetch_message(message_id)
file = await msg.stickers[0].to_file()
await ctx.send(file=file) …
```

feat: to_file for assets, emojis, and stickers

---

docs/migrating_2.rst
nextcord/__init__.py
nextcord/bans.py
nextcord/guild.py
nextcord/http.py
nextcord/iterators.py

https://discord.com/developers/docs/resources/guild#get-guild-bans
`Guild.bans` is no longer a coroutine and returns an AsyncIterator of bans instead of a list.
```py
bans = await guild.bans()
bans = await guild.bans().flatten()  # get the default (first 1000) bans
bans = await guild.bans(limit=None).flatten()  # get all bans
```
More examples:
https://paste.nextcord.dev/?id=1648770287939285

feat!: update bans to use Async Iterator and pagination

---

docs/api.rst
nextcord/interactions.py

Makes a return value for `InteractionResponse.send_message` supporting `edit`, `delete` and `fetch`
Current way of editing, deleting, fetching:
```py
@client.slash_command(guild_ids=[TEST_GUILD_ID])
async def edit_delete_old(interaction: Interaction):
await interaction.response.send_message("Hello World")
await interaction.edit_original_message(content=f"Message Edited")
await interaction.delete_original_message()
@client.slash_command(guild_ids=[TEST_GUILD_ID])
async def fetch_from_interaction(interaction: Interaction):
await interaction.response.send_message("Hello World")
msg = await interaction.original_message()
await msg.add_reaction("\N{THUMBS UP SIGN}")
```
New methods with `PartialInteractionMessage`:
```py
@client.slash_command(guild_ids=[TEST_GUILD_ID])
async def …
```

feat: Make send return a PartialInteractionMessage

---

docs/intents.rst
docs/migrating_2.rst
nextcord/appinfo.py
nextcord/flags.py

Mentions in migrating 2.0 that message content must be enabled if using Intents.default()
Extended deprecation deadline mentioned in docstring (https://github.com/discord/discord-api-docs/discussions/4729)
_Note: This is an API v10 branch PR_

docs: Document migration change to intents

---

nextcord/embeds.py

URL input as arge instead of kwarg because it'll be more convenient to use the function for many users.
Everytime I need to add image or thumbnail in Embed I had to use 
```py
em = Embed(description="Test")
em.set_image(url="https://www.pic.com/image.png")
em.set_thumbnail(url="https://www.pic.com/thumbnail.png")
```
URL as kwarg in set_image function. Now you'll just gonna use like this
```py
em = Embed(description="Test")
em.set_image("https://www.pic.com/image.png")
em.set_thumbnail("https://www.pic.com/thumbnail.png")
```

feat(embeds): set image and thumbnail arent kwarg forced

---

nextcord/asset.py
nextcord/message.py

Adds kwargs to `Asset.to_file` and `Attachment.to_file` for overriding the `filename` or `description` when creating the File.
Fixes to docstrings
```py
@bot.command()
async def asset(ctx: commands.Context[commands.Bot], emoji: nextcord.PartialEmoji):
file = await emoji.to_file(filename="partial_emoji.png", description="Partial Emoji", spoiler=True)
await ctx.send(file=file)
await ctx.send(f"{file.filename} {file.description} {file.spoiler}")
@bot.command()
async def attachment(ctx: commands.Context[commands.Bot], message_id: int):
msg = await ctx.channel.fetch_message(message_id)
if not msg.attachments:
await ctx.send("No attachments found")
return
file = await msg.attachments[0].to_file(filename="attachment.png", description="Attachment", spoiler=True)
await ctx.send(file=file)
await …
```

feat: filename and description kwargs in to_file

---

nextcord/ui/button.py
nextcord/ui/item.py
nextcord/ui/modal.py
nextcord/ui/text_input.py
nextcord/ui/view.py

Adds specific return types to `to_components` and `to_component_dict` methods

refactor: add specific return types for component payloads

---

nextcord/embeds.py

Related to #624 
For consistency with all the other methods in `Embed`, this should also return the new embed.
I tried mentioning this a few times in the relevant PR for the above mentioned issue but it did not get added.
Example
```py
await ctx.send(embed=embed.add_field(name="Test", value=f"field").remove_field(0))
```

Return Embed from `Embed.remove_field`

---

nextcord/message.py

Fixes #651
An attribute occurs when the channel used to create a message is partial (i.e. an Object with an id, but without other attributes such as type). This can be caused by the lib, for example, using `PartialMessageable.send()`:
```py
File "nextcord/ext/commands/core.py", line 165, in wrapped
ret = await coro(*args, **kwargs)
File "test.py", line 33, in test
ret = await partial_channel.send("Hello World")
File "nextcord/dist/../nextcord/abc.py", line 1465, in send
ret = state.create_message(channel=channel, data=data)
File "nextcord/dist/../nextcord/state.py", line 1957, in create_message
return Message(state=self, channel=channel, data=data)
File "nextcord/dist/../nextcord/message.py", line 750, in __init__
if channel.type is not …
```

fix: getting guild when no channel type

---

nextcord/http.py
nextcord/iterators.py
nextcord/scheduled_events.py

Somehow this got by, stop `ScheduledEventIterator` and `ScheduledEventUserIterator` from making infinite loops of requests.
```py
@bot.slash_command(guild_ids=TEST)
async def get_events(inter: nextcord.Interaction):
assert inter.guild is not None
events = await inter.guild.fetch_scheduled_events().flatten()
if not events:
await inter.send("No events found")
else:
await inter.send("\n".join(e.name for e in events))
@bot.slash_command(guild_ids=TEST)
async def get_users(inter: nextcord.Interaction, event_id: str):
assert inter.guild is not None
event = inter.guild.get_scheduled_event(int(event_id))
if not event:
return await inter.send("Event not found")
users = await event.fetch_users().flatten()
if not users:
await inter.send("No users found")
else:
await …
```

fix(scheduled-event-iterator): resolve infinite loop

---

nextcord/client.py
nextcord/iterators.py

Updates the default limit and page size to 200 ([docs](https://discord.com/developers/docs/resources/user#get-current-user-guilds)), and fixes several issues in `GuildIterator` that could break pagination:
- Only use `before` strategy if `before` parameter was specified
- Don't stop after first page if `limit=None` is set
- Always return results in correct order
Resolves #648
<sup>related: DisnakeDev/disnake#526</sup>

fix: guild iterator pagination + limits

---

nextcord/gateway.py

This pull request resolves #660 by making the fallback method `async`. This resolves the issues as the non-async default method returned `None`, which is not `await`able even if the method does nothing.

Fixes gateway voice hook fallback

---

nextcord/application_command.py
nextcord/client.py

Fixed dm_permission causing commands to re-register, fixed app cmds added directly via the Client/Bot decos not fully doing from_callback.
Biggest thing is that App Cmd's with subcommands added via the Client/Bot deco would not fully unpack, causing parameters to not be registered. This fixes that. Could use more testing.

fix(app-cmds): dm_permission causing resync and cmds via bot not registering fully

---

nextcord/__init__.py

This effects the version info printed by `nextcord.__main__.show_version()` or `py -m nextcord -v`
The output currently says "alpha" for nextcord, and not "beta".
```diff
Python v3.10.5-final
- nextcord v2.0.0-alpha
+ nextcord v2.0.0-beta
nextcord pkg_resources: v2.0.0b3
aiohttp v3.8.1
```
We may want to bump the serial code at each release as well when `__version__` is bumped, although it isn't printed by `show_version` and the pkg_resources is printed when the release level is not final so it's not entirely necessary as of now.
Thoughts @ooliver1?

chore: bump version_info to beta release level

---

nextcord/ext/application_checks/core.py

Typings for ext.application_checks.core.bot_has[_any]_role does not include `str`, this fixes that.

fix(app-checks): fix typing for bot_has[_any]_role to allow str

---

nextcord/state.py

fixes #12
get the channel from cache if it exists, else assume it is a DM like before
guild is used if it is found in the channel

fix(interactions): resolve ephemeral channels from cache

---

nextcord/ext/commands/flags.py

fixes #16
only set `flag.annotation` if it has not been provided to the dataclass (`MISSING` by default in `Flag`)

fix(commands): only set flag annotation if not set yet

---

nextcord/ext/application_checks/core.py
nextcord/types/checks.py

Fixes the application checks to allow for normal `async def` functions before they are decorated as a command.
Also allows for cog versions of the above.
(adding `CoroFunc` to the callable union)
the other partially related change is so app checks can be used on cogs w/o type errors

fix(app-checks): change type aliases to allow for normal funcs

---

docs/ext/commands/api.rst
nextcord/ext/commands/bot.py

Since `commands.Bot` is for the ext commands framework which, for the most part, requires message content to work, there can be a warning on startup if `intents.message_content` is not enabled.
This only applies when creating a bot with `commands.Bot` and the `command_prefix` is not an empty iterable or `commands.when_mentioned` since if there's no prefix, there are obviously no commands to listen for and if it is `when_mentioned`, the bot will receive the message content since it will always be mentioned in the messages.
One issue is that DM commands still work without message content intent and it's hard to know if they intend to only have commands work in DMs or not. In this rare case, the user can disable the warning using:
```py
import warnings
warnings.simplefilter("ignore", …
```

feat: Warn when using ext.commands without message content intent

---

nextcord/ui/modal.py
nextcord/ui/view.py

Document `ui.Modal.title` and `.auto_defer` to both `ui.Modal` and `ui.View`, which are public attributes.
Yesterday, someone in the nextcord guild's help channel was unaware the title attribute exists and accidentally overrode it, causing a confusing `TextInput is not JSON serializable`

docs(ui): document public attributes

---

nextcord/types/components.py
nextcord/types/interactions.py
nextcord/ui/item.py
nextcord/ui/modal.py
nextcord/ui/select.py
nextcord/ui/text_input.py
nextcord/ui/view.py

Fixes #668
This refactors Modals to allow any components added to the modal to receive state updates from the interaction callback.
Previously, this was made to work specifically for Text Inputs. In this PR, the logic is moved from text inputs to modals so that all components (i.e. select menus and any new components that are yet to come) will be updated correctly.
This has been tested with TextInput and Select in Modals, and components in Views. (Select menus in Modals are still not available on mobile yet, so they have only been tested on Discord desktop).
The current behavior is that by adding a select menu, it will appear, but after submitting the form, the `select.values` will appear as an empty list.
This PR, while refactoring modals, fixes this issue and will allow select menus to …

feat: refactor modals to fix select menus

---

nextcord/ext/commands/bot.py
nextcord/ext/commands/core.py

fixes #105
copies ctx that is dispatched for `on_command` so a race condition on the race track of `ext.commands` doesnt take over

fix(ext-cmds): copy context before dispatching on_command

---

nextcord/application_command.py

Fixes #697 
Cals the callback modifiers for all types of application commands instead of just Slash commands.

fix: Apply checks to context menu commands

---

nextcord/guild.py

Makes the invite docstring clearer regarding Vanity URL behaviour

docs: Make Guild invite documentation clearer regarding Vanity invites

---

docs/migrating_2.rst

+ Dead link got fixed
+ `Info` got reworded to `Information`
resolves #702

docs(migrating): fix broken link and reword "info"

---

nextcord/ext/commands/converter.py

I wrote `# type: ignore(?!\[)(?!.*#).+$` regex for it, and found only two invalid comments. Hopping this is all.
Fixes #635.

chore: fix incorrect type ignore comments

---

docs/conf.py
docs/migrating_2.rst
nextcord/client.py
nextcord/ext/commands/bot.py
nextcord/message.py
nextcord/widget.py

Fixes several warnings in the docs:
```py
nextcord/nextcord/client.py:docstring of nextcord.client.Client.discover_application_commands:9: WARNING: Inline interpreted text or phrase reference start-string without end-string.
nextcord/nextcord/message.py:docstring of nextcord.Message.thread:1: WARNING: duplicate object description of nextcord.Message.thread, other instance in api, use :noindex: for one of them
nextcord/nextcord/widget.py:docstring of nextcord.WidgetMember.avatar:1: WARNING: duplicate object description of nextcord.WidgetMember.avatar, other instance in api, use :noindex: for one of them
nextcord/nextcord/ext/commands/bot.py:docstring of nextcord.ext.commands.bot.BotBase.application_command_before_invoke:7: ERROR: Unexpected indentation. …
```

docs: fixes several warnings in the docs

---

docs/ext/application_checks/index.rst
nextcord/application_command.py

This adds a new event that is dispatched whenever an application command callback finishes executing with no errors. Closes #676.

feat: add on_application_command_completion event

---

.github/workflows/docs.yml
.github/workflows/lint.yml

This prevents workflows from running twice on PRs from users with write access (for example, 695)
The push event will only trigger when pushing to master and not pushing to a pull request.

ci: prevent workflows from running twice

---

nextcord/ext/commands/converter.py

Fixes #710 
Previously only custom emojis worked with `PartialEmojiConverter`. This adds support for all kinds of unicode emojis.
Note: The regex is a bit loose but all emojis are covered by the regex.
Test code:
```py
@bot.command()
async def test(ctx: commands.Context[commands.Bot], emoji: nextcord.PartialEmoji):
await ctx.message.add_reaction(emoji)
```
The regex has been tested for correctness using a third-party [emoji](https://pypi.org/project/emoji/) package:
```py
from emoji import UNICODE_EMOJI
import re
print(*["" if re.match(r"^[\u0023-\u0039]?[\u00ae\u00a9\U00002000-\U0010ffff]+$", argument) else f"{argument} {[hex(ord(c)) for c in argument]}\n" for argument in UNICODE_EMOJI['en']], sep="")
```

fix: Support unicode emojis in PartialEmojiConverter

---

nextcord/ext/commands/bot.py
nextcord/ext/commands/errors.py

Add a shortcut to command_name in the `CommandNotFound` error. 
I found that using ctx.invoked_with is a bit more "complicated" to figure out than just a `command_name` parameter on the error itself.
resolves #382

feat(commands): CommandNotFound now has command_name shortcut to ctx.invoked_with

---

nextcord/interactions.py
nextcord/types/interactions.py

This uses the newly added `app_permissions` field for the permissions property in Interactions. Closes #720.

feat(interactions): add the app_permissions field

---

nextcord/interactions.py

Just a 1-character change to make the return type display correctly in the docs.
This was a suggested and applied change in #721 but somehow got reverted right before merging?

docs: Fix docstring return type of app_permissions

---

nextcord/ui/modal.py
nextcord/ui/view.py

Currently, the following code found [here](https://paste.nextcord.dev/?id=1656854674165819) will print "Finished waiting" before it prints "Ran timeout". 
This pr fixes this dispatch order for both View's and Modal's so that `on_timeout` is ran first, before anything after `Modal.wait`

fix(ui): Modal & View dispatch orders

---

nextcord/application_command.py
nextcord/ext/commands/bot.py
nextcord/ext/commands/core.py
nextcord/utils.py

Continuation of #695
Uses actual kwargs over pass-down, ignored `**kwargs`.
This is breaking for the same reason as #695.
`_DefaultRepr` inherits from `HelpCommand` so it can continue to be used as the default for `help_command` without type issues.
`Client.__init__` is called manually so `GroupMixin` does not need pass-down `**kwargs` to call `super().__init__` another time unnecessarily. `bot.py` *may* need to have the idea of `BotBase` removed to eliminate similar issues such as this (different PR).
`get_prefix` is edited to use an else clause over overwriting the value so the type checker is aware of the `TypeGuard` which `callable` provides.
`maybe_coroutine` is included to have types so the type checker is at least aware that this will not spit out the original callable, `Any` …

refactor(bot)!: remove the use of **options for options

---

examples/modals/modal.py

Adds an example of a select menu in a modal.
This can possibly wait for Discord to support select menus on mobile before merging so that people don't introduce it in their bots before it's ready.

docs(examples): Add select example in modal

---

nextcord/application_command.py

This PR removes the deprecated `to_register` property from ClientCog.

feat(ClientCog): remove ClientCog.to_register

---

nextcord/ext/commands/bot.py

Fixes help commands. They were broken in #719.
The `@help_command.setter` was not getting called, causing the bot to not have the help command added.

fix(commands): help commands not getting added

---

nextcord/application_command.py
nextcord/types/interactions.py

This adds support for the newly added `min_length` and `max_length` fields in Slash Command options. 
More information about this: https://github.com/discord/discord-api-docs/pull/5143

feat(app-cmds): support min/max length for string options

---

nextcord/interactions.py

Fixes #605
This PR changes the assignment of the following attributes for `Interaction` to try cache before constructing the object: `.message, .user`
This is needed because fields like `status` are not sent in the Interaction member payload but are usually cached.
Preview: ![image](https://i.imgur.com/ql0MZJe.png)
I don't know how to test `.message` and User for `.user` but the correct object is returned.

fix(interactions): get info from cache first if available

---

nextcord/http.py
nextcord/iterators.py

Fix for `after` parameter not working.
As pointed out by DeemonRider on Discord, [audit logs](https://discord.com/developers/docs/resources/audit-log#get-guild-audit-log) do not have an after parameter on Discord.
Additionally, the after parameter was being ignored in the code.
This fixes `AuditLogIterator` to filter out logs after a given point in time when `after` is specified.
```py
@bot.command()
async def logs1(ctx: commands.Context):
"""Get a list of logs."""
count = 0
async for log in ctx.guild.audit_logs(limit=100, after=datetime(2022, 7, 7)):
print(log.id, nextcord.utils.snowflake_time(log.id), str(log.user), log.action)
count += 1
await ctx.send(f"{count} log entries sent to console.")
@bot.command()
async def logs2(ctx: commands.Context):
"""Get a list of logs."""
count = 0 …
```

fix(audit-logs): audit logs after strategy

---

nextcord/interactions.py

Since `Interaction` has a snowflake ID it can be made hashable by inheriting from `Hashable`.
`PartialInteractionMessage` does not have an id, so cannot inherit from `Hashable`.
Changes:
- Interaction now inherits from Hashable
- PartialInteractionMessage now uses the Interaction for checking equality and hash since previously it threw an error
The following error would occur when checking equality of partial interaction messages:
```py
return isinstance(other, self.__class__) and other.id == self.id
AttributeError: 'PartialInteractionMessage' object has no attribute 'id'
```
This is now resolved by implementing the eq, neq, and hash methods using the PartialInteractionMessage's interaction.

feat(interactions): add Interaction hash + fix PartialInteractionMessage hash

---

docs/version_guarantees.rst

Minor version bumps can actually contain breaking changes, this lists in the guarantees that this may be the case.

docs(version_guarantees): add minor may break

---

examples/application_commands/autocompleted_command.py
examples/application_commands/choices.py
examples/application_commands/context_menus.py
examples/application_commands/slash_command.py
examples/application_commands/sub_commands.py
examples/background_task.py
examples/background_task_asyncio.py
examples/basic_bot.py
examples/basic_voice.py
examples/converters.py
examples/custom_context.py
examples/deleted.py
examples/edits.py
examples/guessing_game.py
examples/head_or_tails.py
examples/modals/modal.py
examples/modals/persistent.py
examples/new_member.py
examples/reaction_roles.py
examples/reply.py
examples/secret.py
examples/secure_token_storage.py
examples/views/confirm.py
examples/views/counter.py
examples/views/dropdown.py
examples/views/ephemeral.py
examples/views/link.py
examples/views/persistent.py
examples/views/tic_tac_toe.py

This uses `Intents.message_content` for `ext.commands` examples, removes prefix when not needed, and uses slash commands when `ext.commands` is not being demonstrated.
closes #728
(is a code change but not to the library, its documentation)

docs(examples): add message_content or remove prefix where applicable

---

nextcord/ext/commands/core.py

Return the catchall `**kwargs` to fix `TypeError: GroupMixin.__init__() got an unexpected keyword argument 'name'` and `Client` being initialised multiple times from the blind super init.
This is a temporary fix and I do not like this, but it will have to do for now.

fix(commands): resolve unexpected kwarg errors with GroupMixin

---

nextcord/application_command.py

Re-adds the `app_cmd.qualified_name` property that was accidentally removed in #530. Is this a feat or a fix??

feat(app-cmds): add qualified_name

---

nextcord/application_command.py
nextcord/ext/application_checks/core.py
nextcord/interactions.py

Allows specifying a subclass of `Client` in the `Interaction` type annotation (for example, `Interaction[commands.Bot]`).
This is similar to `commands.Context` which already supports this functionality.
Here is the behavior using the current code *without* this change:
```py
@bot.slash_command()
async def test1(interaction: Interaction, command: str):
bot = interaction.client
cmd = bot.get_command(command)  # ✘ This raises a type warning since Client.get_command is unknown
await interaction.send(f"{command} {'is' if cmd else 'is not'} a valid prefix command")
@bot.slash_command()
async def test2(interaction: Interaction, command: str):
bot: commands.Bot = interaction.client  # ✘ This raises a type warning since Client is incompatible with Bot
cmd = bot.get_command(command)
await …
```

feat(interactions): make Interaction generic on Client

---

nextcord/asset.py
nextcord/file.py
nextcord/message.py

Added force_close to `File` class that will prevent memory leak to occur when a message containing a file is sent if enabled.
`nextcord.abc` calls `File.close()` for each file after the message is sent.
Files bytes could not be deleted after `File.close()` is called.
Causing uploaded files to linger in memory until the garbage collector removes them, usually after a few hours.

feat: add File.force_close to close bytesio files

---

docs/api.rst

The `float` slash option is not with the other standard types, I though this should be fixed.
Issue found by EpicEmre3133#9943

docs(api): move float near to other python types

---

examples/modals/modal.py

Reverts nextcord/nextcord#692
Discord does not yet support selects in modals, the change to this file should wait for it to be ready for production before being added back.

revert: Add select example in modal

---

nextcord/embeds.py

This PR removes `EmptyEmbed` and everything related to it.
`EmptyEmbed` and `Embed.Empty` are kept but are assigned to `None` to make this a non-breaking for users, comparing and using it still works.
One thing that does make it a breaking change is `len()` on an empty field which is not possible on None.

refactor(embeds): deprecate Embed.Empty in favour of None

---

nextcord/message.py

Fixes message initialization failing with threads and no intents by explicitly checking we have a guild object where one is required.
Closes:
- #772

fix(message): initialization failing with threads and no intents

---

nextcord/member.py

Reference: https://github.com/discord/discord-api-docs/commit/e3921e168aa167503ae193439abe70106b58d914
From my understanding, Discord wants users to no longer create mentions with this syntax, however they should still be parsed as user mentions for backward compatibility with older messages.
Currently, when typing a user mention (eg. `<@!310618854734954497>`) the Discord client converts it to `<@310618854734954497>` before sending.
Bots can still send nickname mentions which are treated the same as user mentions, but it seems that Discord is trying to get these types of mentions to stop appearing, so this PR changes `Member.mention` to no longer use the deprecated mention syntax.

refactor(member): remove deprecated nickname mention syntax

---

nextcord/application_command.py

Does the following:
* Stops the slash command payload from always setting "options", even when they have no options or children.
* This fixes possible needless resyncing of option-less commands.
* This fixes lazy loading of option-less commands.
* Sorts the command option payload "channel_types" list due to Discord sending them back sorted.
* This fixes needless resyncing of commands with an option that has channel_types set out of order.
* This fixes lazy loading of ^

fix(app-cmds): stop syncing on no options/channel type sorting

---

nextcord/http.py

Fixes #795 
This should remove the components and embeds but since #608 it does not.
```py
@bot.command()
async def test(ctx):
view = nextcord.ui.View()
view.add_item(
nextcord.ui.Button(label="Test", style=nextcord.ButtonStyle.link, url="https://google.com")
)
embed = nextcord.Embed(title="Test", description="Test")
msg = await ctx.send("test", view=view, embeds=[embed])
await msg.edit(
"test - should have no buttons or embeds",
view=None,
embeds=[],
file=await ctx.author.display_avatar.to_file(),
)
```
Some of the refactoring done in #608 to reduce repetition of handling message parameters used code meant for sending for editing messages with files and these did not check for `is not None`, but rather for truthy values, meaning that empty lists do not get passed in payloads, so you …

fix: Empty lists not sent in payload when files sent

---

nextcord/application_command.py

Adds `SlashApplicationCommand.get_mention` and `SlashApplicationSubcommand.get_mention` for getting the string that allows you to mention the application command.
Note: This is not a property since commands can have multiple IDs if they are in multiple guilds. The naming `get_mention()` is used instead of `mention` to make this distinction.
This also adds `SlashApplicationSubcommand.command_ids` (a shortcut to the parent command's IDs) in order to simplify the implementation making it so the same code can be used for `SlashApplicationCommand` and `SlashApplicationSubcommand`
Usage:
```py
@bot.slash_command()
async def cmd1(interaction: Interaction):
await interaction.send(f"{interaction.application_command.get_mention()} {cmd1.get_mention()}") …
```

feat(app-cmds): add get_mention to Slash Commands

---

examples/custom_interaction.py
nextcord/client.py
nextcord/state.py

Adds the ability to provide a custom interaction class which the library will use.
Closes #757 
Note the return type of `get_interaction` varies from it's `get_context` counterpart as this was the only way I could find that would appease `task pyright`. If you are aware of an alternative where the return type can simply be `InterT` please let me know.
```python
import os
from nextcord import Interaction, Client
TESTING_GUILD_ID = 500525882226769931
class CustomInter(Interaction):
@property
def custom_prop(self) -> bool:
return True
class CustomClient(Client):
def get_interaction(self, data, *, cls=Interaction):
return super().get_interaction(data, cls=CustomInter)
client = CustomClient()
@client.event
async def on_ready():
print("...") …
```

feat: add the ability to use custom interactions

---

nextcord/client.py
nextcord/state.py

Fixed the issue regarding delete_application_commands where commands could not be deleted from one guild specifically.
This was caused by a hardcoded value of None for the guild_id being passed to delete_application_command. Additionally, 
logging messages and error messages were added for when a non-global command is attempted to be globally unregistered,
which simply caused a KeyError exception before.

fix(app-cmds): delete_application_commands for guild commands

---

nextcord/client.py
nextcord/gateway.py
nextcord/http.py

Resolves #762 
Implements new gateway resume flow by using the `resume_gateway_url` from the `READY` event

feat: support resume_gateway_url for resuming

---

nextcord/client.py

This PR fixes an issue where two application commands with the same signatures could be registered. What happens now is a `ValueError` exception is raised when two application commands with the same signatures are detected.

fix(app-cmds): two application commands with the same signatures could be registered

---

docs/conf.py
setup.py

sphinx-doc/sphinx#10807 decided to add a feature which was enabled by default.
This feature however increased the toctree's height and width by a huge amount - a breaking change.
This locks sphinx to an exact version to reduce issues like this again.

docs: lock sphinx and fix toctree

---

nextcord/enums.py

Small typo noticed in the enums PR (#801). This causes an issue using `<=` with an `UnknownEnumValue` and an `int` or `string`.

fix(enums): resolve less than or equal comparison

---

nextcord/application_command.py

<https://github.com/discord/discord-api-docs/issues/5433#issuecomment-1266168023>
This PR fixes the following traceback due to the Discord client sending invalid option data in autocomplete.
```py
File "/root/.cache/pypoetry/virtualenvs/vibr-TFcQMFAJ-py3.9/lib/python3.9/site-packages/nextcord/application_command.py", line 1609, in handle_value
value = int(value) if value != "" else None
ValueError: invalid literal for int() with base 10: 'd'
```

fix(app-cmds): temporarily fix autocomplete integer conversion

---

nextcord/application_command.py

Closes #798
This documents the `SlashCommandMixin.children` property.

docs(app-cmds): document SlashCommandMixin.children

---

nextcord/client.py

This fixes the `nextcord.new` mistake in `Client.fetch_template`. Assuming that the Search & Replace replaced that on the big rename.

docs(client): fix nextcord.new mistake

---

nextcord/client.py
nextcord/state.py
nextcord/ui/view.py

This implements `remove_view` and `remove_modal` in `nextcord.Client` and `nextcord.ConnectionState`. Closes #425.

feat(client): add Client.remove_view and Client.remove_modal

---

nextcord/application_command.py
nextcord/guild.py

Fixes a docs "unknown directive" issue:
```rst
nextcord/nextcord/application_command.py:docstring of nextcord.SlashApplicationCommand.children:3:
WARNING: Unknown directive type "versionupdated".
.. versionupdated:: 2.3
``.children`` is now a read-only property.
```
Also added missing version directives to Guild.ban.

docs: Fix version directives in documentation

---

nextcord/application_command.py

Seems like the temporary fix in https://github.com/nextcord/nextcord/pull/835 (unreleased) caused `int` typehints to start throwing an error.
It seems like this occurs whether the numbers entered are positive or negative.
The code seems to previously be assuming the value is always a string and non-negative, when it is actually not necessarily either of those.
Traceback for issue resolved ([discord.com/channels/881118111967883295/1033104159584555189/1033104420935839884](https://discord.com/channels/881118111967883295/1033104159584555189/1033104420935839884))
```
Ignoring exception in on_interaction
File "nextcord/client.py", line 502, in _run_event
await coro(*args, **kwargs)
File "nextcord/client.py", line 1948, in on_interaction
await …
```

fix(app-cmds): Resolve error with integer conversion in slash commands

---

nextcord/application_command.py

`on_autocomplete` was previously undocumented besides an example in the `examples` folder. This adds a docstring to `on_autocomplete` so it appears in the API Reference.

docs(app-cmds): document on_autocomplete decorator

---

nextcord/application_command.py
nextcord/client.py
nextcord/ext/commands/bot.py
nextcord/http.py
nextcord/interactions.py
nextcord/iterators.py
nextcord/member.py
nextcord/shard.py
nextcord/state.py

Some imports were duplicated in `TYPE_CHECKING` and were not necessary. These imports have been removed.
Additionally, some f-strings had no placeholders so did not need to use f-strings. These have been converted to regular strings.

refactor: Remove duplicate imports and f-strings with no placeholders

---

docs/ext/commands/commands.rst
docs/whats_new.rst
nextcord/application_command.py
nextcord/auto_moderation.py
nextcord/channel.py
nextcord/client.py
nextcord/embeds.py
nextcord/ext/application_checks/core.py
nextcord/ext/commands/bot.py
nextcord/ext/commands/converter.py
nextcord/ext/commands/core.py
nextcord/ext/tasks/__init__.py
nextcord/guild.py
nextcord/invite.py
nextcord/iterators.py
nextcord/raw_models.py
nextcord/state.py
nextcord/threads.py
nextcord/utils.py
nextcord/widget.py

Made 100+ fixes to single-backtick words in rst files to double-backtick phrases or reference links depending on the case.
This helps with readability since single-backtick phrases are italicized rather than set in inline-codeblocks. 
A few additional small docs fixes were also made (eg. missing colon, etc.) in certain cases.

docs: Fix single-backtick words to double-backtick or links

---

nextcord/ext/commands/flags.py
nextcord/utils.py

This closes #866 by migrating the syntax for ``flags.py`` inline with changes to Python 3.11

fix: Python3.11 dataclass changes

---

nextcord/guild.py

Add the `Optional` annotation for limit in two cases, since it was both times type hinted to be a int, but also accepted None for no limit.
Testing is not needed, since its just annotation for values that already are used for it.

refactor(guild): use Optional for limit kwargs

---

nextcord/application_command.py

* Adds missing documentation for `BaseApplicationCommands.checks`.
* Moves `OptionConverter` docstring from init to the class scope so it appears in the docs.
* Added short docstrings to `BaseApplicationCommands`, `SlashApplicationCommand`, `SlashApplicationSubcommand`, `UserApplicationCommand`, `MessageApplicationCommand`

docs(app-cmds): Document .checks, OptionConverter, Commands

---

nextcord/application_command.py

Adds PEP 604 support to application commands, allowing the Python 3.10 style of unions.
Example: `arg1: str | None`

feat(app-cmds): add support for 3.10 unions

---

nextcord/abc.py

This PR fixes a crucial issue with #805 where an import previously imported in the `TYPE_CHECKING` section was used in a section of code outside of type hints.

fix(abc): move import from TYPE_CHECKING to runtime

---

setup.py

Use `aiohttp[speedups]` to depend on aiohttp's list, instead of defining them ourselves.
This means that aiohttp's qualifier to not install `cchardet` since it is not maintained, and so `nextcord[speed]` works on 3.11.

build: use aiohttp[speedups] so cchardet isnt installed >=3.10

---

nextcord/application_command.py

This is a CRUCIAL problem with #736 that was not spotted during the review phase.

fix(app-cmds): typing module is not imported

---

nextcord/components.py
nextcord/ui/button.py
nextcord/ui/item.py
nextcord/ui/modal.py
nextcord/ui/select.py
nextcord/ui/text_input.py
nextcord/ui/view.py

This improves public-facing annotations in the ui module.
The overall pyright type completeness score increases by 2.3%.
Unlike #877, this does not use `pyright: strict`, since there are significant archtectual changes required to get strict to be happy, such as importing and using private members, and using raw `**kwargs` for 'underlying' objects.

refactor(ui): improve public annotations

---

docs/api.rst
nextcord/audit_logs.py
nextcord/enums.py

Closes #817 
Adds `auto_moderation_flag_to_channel` and `auto_moderation_user_communication_disabled` audit log event types
https://github.com/discord/discord-api-docs/blob/main/docs/resources/Audit_Log.md

feat(audit-logs): `auto_moderation_flag_to_channel`, `auto_moderation_user_communication_disabled` types

---

nextcord/types/checks.py

This module contained imports in TYPE_CHECKING were used outside of annotations, causing the module to not import properly with a NameError.
```py
>>> import nextcord.types.checks
File "<stdin>", line 1, in <module>
File "nextcord/types/checks.py", line 39, in <module>
Callable[[ClientCog, Interaction], MaybeCoro[bool]], Callable[[Interaction], MaybeCoro[bool]]
NameError: name 'ClientCog' is not defined
```
Since all of the symbols in this file are only imported in TYPE_CHECKING, they don't need to be defined outside.

fix: Unable to import nextcord.types.checks

---

docs/interactions.rst
nextcord/application_command.py
nextcord/client.py
nextcord/ext/commands/bot.py
nextcord/shard.py
nextcord/state.py

This PR adds a new parameter to `Client` and `AutoShardedClient` named `default_guild_ids` that acts as the default guild ids for application commands that don't have any guild ids set. Closes #395.

feat(app-cmds): default_guild_ids

---

nextcord/application_command.py

This PR fixes (yet) another problem with #736 where the `issubclass` clause did not first check if the annotation was even a class.

fix(app-cmds): issubclass check failed w/ normal objects

---

docs/api.rst
nextcord/enums.py
nextcord/flags.py

This implements the `ACTIVE_DEVELOPER` flag from https://github.com/discord/discord-api-docs/pull/5619 and https://github.com/discord/discord-api-docs/pull/5620 (Not merged yet).

feat(flags): add `ACTIVE_APPLICATION` & `ACTIVE_DEVELOPER` flags

---

nextcord/ext/application_checks/errors.py

I just swapped the type hints, since they were the wrong way around. The doc string was right before, but the actual type hints were swapped for some reason. My linter was screaming at me, that's how I noticed.

refactor(app-checks): correctly type ApplicationCheckAnyFailure

---

nextcord/ext/application_checks/errors.py
nextcord/ext/commands/errors.py

Removes the use of Snowflake and SnowflakeList, since they are used wrongly. Also makes that super explicit type hinting a consistent thing over the whole file.
Testing not needed, just type hinting for already used things.

refactor: use explicit union[str, int] with *HasRole errors

---

nextcord/abc.py

This PR types the parameters of the actual implementation (aka not overloaded version) of `GuildChannel.set_permissions`. The actual implementation's parameters are changed slightly to include a catch-all variable keyword parameter because of how different the two other overloads are.
Closes #839.

typing(abc): type set_permissions parameters

---

.github/workflows/lint.yml
pyproject.toml
setup.py
unaliased-setup.py

Added 3.11 to the list of versions linted.
Also marked it as a supported version.
**Testing should be done in 3.11 before this is merged.**

ci: add support for linting Python 3.11 

---

nextcord/state.py

Fixing last_message_id not being updated for VoiceChannel

fix: last_message_id not updating on VoiceChannel

---

nextcord/application_command.py

When lazy loading, if a command has at least one optional parameters and at least one of the optional parameters is included in the initial lazy load, Nextcord will error due to a missing `.items()` in a for loop. This PR fixes that.
To test:
1: Make a command with at least one optional argument.
2: Start up your bot with all rollout settings set to `False`.
3: Use the command, giving the optional argument a value.

fix(app-cmds): Fix optional params causing error when lazy loading.

---

nextcord/ui/select/channel.py

This moves `from ...abc import GuildChannel` out of the `if TYPE_CHECKING` statement. As this causes errors during run time. Fixes nextcord#919

fix(select-channel): import GuildChannel at runtime

---

nextcord/iterators.py

This PR fixes a crucial bug with #872 in 3.9+ where it throws the following runtime error when the `nextcord` module is imported:
```python
Traceback (most recent call last):                                                        
File "/root/k", line 1, in <module>
import nextcord
File "/usr/local/lib/python3.10/dist-packages/nextcord-2.4.0a4182+gbb812e66-py3.10.egg/nextcord/__init__.py", line 24, in <module>
from . import abc, opus, ui, utils
File "/usr/local/lib/python3.10/dist-packages/nextcord-2.4.0a4182+gbb812e66-py3.10.egg/nextcord/abc.py", line 52, in <module>
from .iterators import HistoryIterator
File "/usr/local/lib/python3.10/dist-packages/nextcord-2.4.0a4182+gbb812e66-py3.10.egg/nextcord/iterators.py", line 170, in <module>
class _MappedAsyncIterator(Generic[T, OT], …
```

fix(iterators): switch _MappedAsyncIterator inheritance order

---

nextcord/ext/commands/core.py

This PR fixes a problem with #894 where an attribute in `Command` was changed to be set directly to the underlying private attribute which missed the property callback which sets another crucial attribute.

fix(commands): stop setting private attribute directly

---

nextcord/ui/select/mentionable.py
nextcord/ui/select/role.py

This PR fixes an issue with #848 where type checking imports were used at runtime.
In order to merge this PR, two different people will have to test it to ensure that I have not missed any imports.

fix(ui.select): type checking imports used at runtime

---

nextcord/http.py
nextcord/iterators.py

Since the after parameter in audit log retrieval is documented, this can be used over filtering, reversing and fetching tons of logs.
<https://github.com/discord/discord-api-docs/commit/38f01b07531b672880e434692d215233e45eb0db>
[Test Code](https://paste.nextcord.dev/?id=1673044721454197)

refactor: use audit log `after` query param

---

docs/api.rst
nextcord/state.py

Closes #962.
Since dispatching `on_thread_join` will cause a breaking change, it is dispatched in both conditions for now.
**Test Code:** <https://paste.nextcord.dev/?id=1673220045815470>

feat(state): add on_thread_create

---

docs/api.rst
nextcord/client.py
nextcord/http.py

This adds a new ratelimit event that is dispatched whenever an HTTP request exhausts a bucket or gets a 429 response. Closes #154.

feat: http ratelimit events

---

nextcord/channel.py

Added In The Create_Webhook For Text Channels To Forums And Voice Channels.
Weirdly on the voice channel, the webhook comes back good and does work, but it doesn't show in the Integration tab when editing the channel.

feat: add create_webhook in forum & voice channels

---

nextcord/abc.py

Similar to #695 and #719, this removes the use of `**` catchall options for `abc.GuildChannel.move`.

refactor(abc): remove the use of ** for GuildChannel.move

---

nextcord/auto_moderation.py
nextcord/types/auto_moderation.py

This PR adds support for regex patterns in automod trigger metadata. Closes #884.

feat(automod): regex patterns

---

nextcord/application_command.py

microsoft/pyright#3799
`__class_getitem__` is apparently for generics,
This means that pyright believes they are `Type[Self]` not `Type[int]|Type[str]`.
Using a metaclass means pyright recognises parameters as the correct type.

refactor(app-cmds): use a metaclass for String and Range

---

nextcord/iterators.py

This imports `nextcord.types.user.PartialUserPayload` during runtime in nextcord/iterators.py. As it is actually used in the code and not only for the sake of typehinting.
Introduced in #872
Fixes #984

fix(iterators): import PartialUserPayload during runtime

---

README.rst

This adds the missing `nextcord` import that was used for `nextcord.Interaction` in the readme file.

docs(README): add missing nextcord import

---

nextcord/webhook/async_.py
nextcord/webhook/sync.py

Values in `_locks` are no longer required when a webhook has been used fully. Since interactions use webhooks, I have a couple hundred thousand `Lock` objects in memory that are not needed.

refactor(webhook): use WeakValueDictionary for _locks

---

nextcord/application_command.py

Fixes an issue where the bot would crash if `nextcord.Interaction[commands.Bot]` or similar is used as the interaction annotation. This is the fully qualified annotation which specifies the client type and is recommended so should be supported.
Example where it is broken:
```py
class PingCog(commands.Cog):
@nextcord.slash_command()
async def ping(self, interaction: nextcord.Interaction[commands.Bot]):
await interaction.send("Pong")
```
Error traceback:
```py
File "python/lib/python3.10/site-packages/nextcord/ext/commands/bot.py", line 775, in _load_from_module_spec
setup(self, **extras)
File "/app/modules/ping/cog.py", line 30, in setup
bot.add_cog(PingCog(bot))
File "python/lib/python3.10/site-packages/nextcord/ext/commands/cog.py", line 182, in __new__ …
```

fix: Support Interaction annotation with client type specified

---

nextcord/gateway.py

This PR updates Nextcord to use the new UDP packet format for [discovering your external IP address and port](https://discord.com/developers/docs/topics/voice-connections#ip-discovery) against Discord's VoIP servers.
Discord announced in their guild that on **March 15th, 2023**, all VoIP servers would be updated to **only** accept the 74-byte packet length, and would no longer accept the 70-byte packet length format which nextcord currently uses.
disnake made [a similar change](https://github.com/DisnakeDev/disnake/pull/967) to their library in their most recent release.
- [?] This PR is a breaking change (e.g. methods or parameters removed/renamed)

refactor(gateway): switch to 74 byte UDP packet format for IP discovery

---

nextcord/gateway.py

As it is a required parameter, see https://discord.com/developers/docs/topics/voice-connections#speaking.
Additionally included in this PR is the elimination of an unnecessary call to `DiscordVoiceWebSocket.speak` - see the commit message of https://github.com/nextcord/nextcord/commit/5d7b63d10ca6408194e1f1b7a8688c0934127bbf for why.
We found that without the ssrc change, [our Discord bot](https://github.com/anoadragon453/busty/) would fail to play audio after joining a stage. Regular voice channels were fine, however. Moving the bot between the audience and the stage seemed to be a workaround, but didn't in all cases.
The issue also seemed to only affect certain Discord guilds, for whatever reason, and only cropped up in the past month, suggesting that Discord has changed something on …

fix(voice): include ssrc parameter when sending a `SPEAKING` payload

---

nextcord/channel.py

The `invitable` parameter was not present in the `TextChannel.create_thread` method for some reason even if the underlying state supported it, so I added it.

refactor(channel): add invitable argument in create_thread method

---

nextcord/channel.py
nextcord/threads.py
nextcord/types/channel.py

Fixed ForumChannel.available_tags only returned last tag by wrong id: used wrong dict to get id
Fixed Thread.applied_tags and Thread.applied_tag_ids returned empty list: used non-existent key in getting tags data from payload
ForumTag id is no longer optional when getting from payload

fix: ForumChannel and Thread returning wrong ForumTags

---

examples/secure_token_storage.py

Prefer os.environ over os.getenv for the token example. I had the reasoning laid out here but `gh` fucked up the request and deleted my message, tl;dr it gives a better error.

chore: prefer os.environ

---

nextcord/state.py

Reflect https://discord.com/developers/docs/resources/audit-log#audit-log-entry-object
Fix issue like detailed in https://discord.com/channels/881118111967883295/1084474550345023638

fix(state): hard crash when user_id is None

---

nextcord/file.py

Add a context manager to `nextcord.File`. This will automatically call `close()` on the file when the context manager exits scope.
Also change `force_close` to be optional default to None so that we can set `force_close` to True when using context manager if `False` was not provided to init.
```python
file = nextcord.File(filepath)
await channel.send(file=file)
file.close()
```
```python
with nextcord.File(filepath) as file:
await channel.send(file=file)
```

feat(file): add context manager to File

---

nextcord/application_command.py

Reverts nextcord/nextcord#986
The PR introduced unwanted changes which break end user bots

revert: "docs(app-cmds): document SlashCommandMixin.options"

---

nextcord/audit_logs.py
nextcord/types/audit_log.py

Fixes #1038. There's a possibility that `channel_id` for being None when a nickname change was blocked by AutoMod and this has been logged in the AutoMod log channel.
Also removes some repetition in audit_logs.py
Testing code: https://paste.nextcord.dev/?id=1682809496392755

fix(audit_logs)!: channel_id can be None due AutoMod blocking nickname changes

---

nextcord/flags.py

The suppress notifications option is from discord/discord-api-docs#5910.
Bitshifted values seemed to have been missed in #911 as this is a flag

feat(flags): add missing MessageFlags values

---

nextcord/guild.py

Update the file limits to the 25MiB default limit documented in discord/discord-api-docs#6078
The format of `_GuildLimit` usage has also been changed to make sense when reading it, instead of being magic numbers.

fix(guild): update guild limits to 25MiB default

---

nextcord/abc.py

Fixes #55
This basically removes the part of the doc where it says that the top channel's position is 0. As the issue is that the channel positions are put in random orders (at least, from my understanding from the PR that #55 links).
So that it does not imply anything about what channel comes first and so on.

docs(abc): remove the position specification

---

nextcord/abc.py
nextcord/interactions.py
nextcord/message.py
nextcord/ui/view.py

Adding prevent_update to View. Option preventing storing permanent views for separate messages by default.
(since there's no limit to how many different buttons get stored, and if not stopped properly can cause issues over time when running a bot for long periods without reboot, and users are not notified of these being stored)

feat(View): add prevent_update param

---

nextcord/application_command.py
nextcord/client.py
nextcord/ext/commands/bot.py
nextcord/state.py

This PR moves global application command checks to `nextcord.Client` (from `BotBase`), same for storage (from `ConnectionState`(why?))
#956

refactor(app-cmds): move global checks to Client

---

nextcord/guild.py
nextcord/types/guild.py

The documentation specifies that this field will always be avaliable, but apparently not.
This PR no longer uses key access to get the field in case it happens to be null when there is an unavaliable guild payload.
Continuation of #1067

fix(guild): premium_progress_bar_enabled can be null

---

.github/PULL_REQUEST_TEMPLATE.md

Using conventional commits means these are no longer needed.
- Fixes are represented as `fix:`
- New features are represented as `feat:`
- Breaking changes are represented as `BREAKING CHANGE:` and/or `<type>!:`
- Other types are represented as `docs:`, `chore:`, `refactor:`, ...
The checklist has been commented out, to be uncommented when required.
Inspired by <https://raw.githubusercontent.com/eludris/eludris/main/.github/PULL_REQUEST_TEMPLATE.md> from @spifory

chore: remove redundant pr template checkboxes

---

nextcord/application_command.py

When using either a `nextcord.User` or `nextcord.Member` item within autocomplete there is a chance that the required data is missing due to discord not sending the data. This PR fixes the raw tracebacks and instead takes a best effort approach to attempting to get a valid object from cache before returning atleast a `nextcord.Object` object.
```py
@client.slash_command()
async def test(
interaction: nextcord.Interaction,
member: nextcord.Member = nextcord.SlashOption(
name="member", description="Select member", required=True
),
warn: int = nextcord.SlashOption(name="warn", description="Warn", required=True),
):
print(type(member))
@test.on_autocomplete("warn")
async def warn_autocomplete(interaction: nextcord.Interaction, warn: int, member: nextcord.Member):
print(type(member))
return …
```

fix(app-cmds): incomplete payloads giving tracebacks within autocomplete

---

nextcord/guild.py
nextcord/http.py

discord/discord-api-docs#5994
This PR adds the missing `default_forum_layout` parameter to `Guild.create_forum_channel`.
This attribute was added in #942.
I have not had time to test this.

feat(guild): add default_forum_layout to create_forum_channel

---

nextcord/user.py

This makes `BaseUser.discriminator` use key access instead of `.get`.
The issue was initially caused by #1061 where at first I had planned for the discriminator to be None, but forgot it would be a breaking change.

refactor(user): use key access for `BaseUser.discriminator` 

---

nextcord/ext/commands/bot.py

Looks like there is an extra dot(.) inside `BotBase.add_cog` docstring

docs: Fix docstring in add_cog

---

nextcord/application_command.py

Fixes #1045
`from_autocomplete_callback` is not getting called and `autocomplete_options` is not getting populated when `autocomplete_callback` is supplied to a SlashOption rather than using the decorator. This causes other options from the command to be inaccessible from the autocomplete callback method (see linked issue).
Replaces `iscoroutinefunction` check in `SlashCommandOption` with a call to `self.from_autocomplete_callback(self.autocomplete_callback)` which includes the `iscoroutinefunction` check and also populates the `autocomplete_options` field to have the other options in the command so they can be accessed later when the callback is called (see [`from_autocomplete_callback`](https://github.com/DenverCoderOne/nextcord/blob/c2af2acdee302b0056dfb5f7ede934f20413f971/nextcord/appl …

fix(app-cmds): unfocused options not getting passed in autocomplete callback

---

docs/api.rst

- discord/discord-api-docs#6265
Standard stickers are free now, so the documentation must no longer specify that they are for Nitro users.

docs: update `StickerType.standard`

---

nextcord/raw_models.py
nextcord/state.py

Previously, it was not possible to see what user left. This adds the attribute to `RawMemberRemoveEvent`, using a full user object ( :D finally a non-partial ) to get a full `User`.

feat(raw-models): add guild and user attr to RawMemberRemoveEvent

---

nextcord/scheduled_events.py
nextcord/types/scheduled_events.py

[Docs](https://discord.com/developers/docs/resources/guild-scheduled-event#guild-scheduled-event-object)
it seems like the `TypedDict` and docs were mismatched, causing `TypeError: nextcord.scheduled_events.EntityMetadata() argument after ** must be a mapping, not NoneType`

fix(scheduled-events): sort out optionals and nullables

---

examples/application_commands/localization.py

Makes examples/application_commands/localization.py make use of the `Locale` enum's values instead of a hard-coded string.
Completes #1091
<!--

chore(examples): use `Locale` enum instead of strings

---

nextcord/application_command.py
nextcord/components.py

Types are now hard coded onto menus and are also read only, this resolves an issue where the underlying constructor would try to override that attribute resulting in an error
Closes #1103 
<!--

fix: menu assigning failing due to read only attributes

---

nextcord/ui/select/mentionable.py
nextcord/ui/select/user.py

For some time now, whenever building the documentation, you would get these warnings:
```
<path>/nextcord/nextcord/ui/select/user.py:docstring of nextcord.ui.UserSelect.values:1: WARNING: 
more than one target found for cross-reference 'User': nextcord.abc.User, nextcord.User, nextcord.user.User
<path>/nextcord/nextcord/ui/select/user.py:docstring of nextcord.ui.UserSelectValues.users:3: WARNING: 
more than one target found for cross-reference 'User': nextcord.abc.User, nextcord.User, nextcord.user.User
<path>/nextcord/nextcord/ui/select/mentionable.py:docstring of nextcord.ui.MentionableSelect.values:1: WARNING: 
more than one target found for cross-reference 'User': nextcord.abc.User, nextcord.User, nextcord.user.User
<path>/nextcord/nextcord/ui/select/mentionable.py:docstring of …
```

docs: fix build warnings

---

nextcord/client.py
nextcord/http.py
nextcord/iterators.py

Implements discord/discord-api-docs#5628
In case you're wondering, "why is the default for `with_counts` `False`?"
Well that is because the default on the documentation `false`, so just for the sake of consistency, that is why the default is `False`.

feat(iterators): add `GuildIterator.with_counts`

---

nextcord/flags.py

Fixes nextcord#1037
This removes the `ApplicationFlags.active` flag. While this _is_ a breaking change, there is no reason for it to be in the lib at all because it never existed, as shown by [this comment](https://github.com/discord/discord-api-docs/pull/5620#issuecomment-1355412285).
The PR adding this, nextcord#897 was merged too early, so I assume that's why this existed in nextcord in the first place.

refactor(flags)!: remove `ApplicationFlags.active`

---

nextcord/utils.py

Create a new function `format_ts` that can format a unix timestamp, format_dt can use this function too to reduce code duplication.
Closes #1085

feat(utils): add format_ts

---

nextcord/activity.py

This PR documents the `state` attribute on `CustomActivity` and makes it fallbacks to `name` instead of `None` if not provided.
This allows users to do the following:
```py
nextcord.CustomActivity(
name = "Nextcord is the best!"
)  
```
Instead of:
```py
nextcord.CustomActivity(
name = "Custom Status",
state = "Nextcord is the best!"
)
```

fix: make `state` fallback to `name`  for CustomActivity

---

docs/api.rst
nextcord/flags.py
nextcord/member.py
nextcord/types/member.py

Relevant link to API Docs:
- https://discord.com/developers/docs/resources/guild#guild-member-object-guild-member-structure
- https://discord.com/developers/docs/resources/guild#guild-member-object-guild-member-flags
This PR adds support for getting a member's flags via the matching attributes.
I have not tested this but.. most of the code is from **my** PR to discord.py - https://github.com/Rapptz/discord.py/pull/9204 which was fully tested.
Adds the following:
- Classes:
- `MemberFlags`
- Attributes to nextcord.Member:
- `_flags`
- `flags` (property)
- Kwargs to nextcord.Member.edit:
- `flags`
- `bypass_verification`
- Fields to `PartialMember` (type):
- `flags`
- Possible attrs for `on_member_update` (docs):
- `flags`

feat(flags): add MemberFlags and relevant fields

---

nextcord/iterators.py

Fix `AuditLogsIterator` checking for the length of the data returned, instead of the length of the entires returned. (Fixing not allowing more than 100 entries to be queried)

fix(iterators): allow querying over 100 audit log entries

---

nextcord/http.py

This PR removes `http._modify_api_version`. It was a temporary workaround in the past around the message content intent changes that were made in API v10. Nowadays, it has no use and it's not recommended to use it, according to its own documentation.
<!--

refactor: remove _modify_api_version

---

CONTRIBUTING.md

`removal` is a useful commit type over `refactor!` as it is more explicit on what the actual type of refactor this is - removal of API code.
<!--

docs(contributing): add removal conventional commit type

---

nextcord/ui/modal.py

This PR specifies what items modals support in `Modal.add_item`.

docs(ui): specify what items modals support

---

nextcord/ext/commands/bot.py

Adds "extras" kwarg to bot.reload_extension method, this allows users to pass kwargs to a cog's setup function when reloading a cog.
Closes #1154

feat(commands): add extras kwarg to bot.reload_extension

---

nextcord/member.py
nextcord/user.py

Without this change the display_name property returns a nickname if present, if not just the username (which is the hidden away username). It doesn't consider the "Display Name" also known as global_name at all.
In my opinion, that is bad behavior, because the global_name takes priority in the Discord UI over the username if it exists, so it should here as well. After all, when people use this property, they want the name the person is displayed as, not the hidden away unique username.

feat(User & Member): update display_name method to include global_name

---

nextcord/gateway.py

Prevents the bot from crashing with `aiohttp.http_websocket.WebSocketError: Received fragmented control frame`
Ported from Discord.py : https://github.com/Rapptz/discord.py/commit/163a86c4a031f7ecd856f45a74da47e63b17bb16
Closes #1170

fix(DiscordWebSocket): Raise WebSocketClosure on protocol level errors

---

nextcord/user.py

Implements discord/discord-api-docs#6710 by adding a `banner` parameter on ClientUser.edit

feat(user): add `banner` param to ClientUser.edit

---

.github/workflows/lint.yml
pyproject.toml

> **Note**
> This too relies on #1126 as without poetry, the 3.12 PyPI specifier would have to be added to package metadata as well. This is a draft until that is merged.
[Python 3.12 is now stable :rocket:](https://docs.python.org/3.12/whatsnew/3.12.html). The optimisations are amazing but there's not all too much to benefit from otherwise this time round. Nearly all of the deprecations do not affect us, and there are only module removals (`asynchat`, `asyncore`, `imp`, `distutils`).
The [`get_event_loop`](https://github.com/python/cpython/issues/100160) changes may need some refactoring for both the examples, `Client` and `Webhook`s, as that will eventually not create a new loop implicitly (slightly irritating but makes sense).
[`datetime.datetime.utcnow` and `datetime.utcfromtimestamp` …

chore: add 3.12 to supported lists

---

nextcord/application_command.py
nextcord/client.py
nextcord/embeds.py
nextcord/guild.py
nextcord/member.py

This PR removes all deprecations from 2.x.
What has been removed:
- BaseApplicationCommand
- `check_against_raw_payload` -> `is_payload_valid`
- `get_guild_payload` -> `get_payload(guild_id)`
- `global_payload` -> `get_payload(None)`
- Client
- `persistent_views` -> `views(persistent=True)`
- `deploy_application_commands` -> `discover_application_commands`
- `delete_unknown_application_commands` -> `sync_application_commands`
- `associate_application_commands` -> `sync_application_commands`
- `update_application_commands` -> `sync_application_commands`
- `add_startup_application_commands` -> `add_all_application_commands`
- `rollout_application_commands` -> `sync_application_commands`
- Embeds
- `EmptyEmbed` -> `None`
- `Embed.Empty` -> `None`
- `Guild/Member.ban`
- `delete_message_days` …

removal!: deprecations from 2.0

---

nextcord/auto_moderation.py
nextcord/types/auto_moderation.py

Adds support for the `custom_message` property in the automod action metadata. Closes #1191.

feat(auto_moderation): Add custom_message support

---

nextcord/widget.py

This is a follow-up to #1123 . I had suggested to also apply that change to WidgetMember as it also has a display_name property, but that PR got merged without it.
This PR applies that same change as Member to WidgetMember : the display_name property will return the name using the following hierarchy:
1. Guild specific nickname
2. Global Name (also known as 'Display Name' in the Discord UI)
3. Unique username

feat(widget): update display_name method to include global_name

---

nextcord/enums.py
nextcord/invite.py
nextcord/types/invite.py

Implements discord/discord-api-docs#6568 by adding a `type` attribute to the `Invite` class.

feat(invite): add `type` attribute

---

nextcord/auto_moderation.py

Fix a typo in `AutoModerationActionExecution`'s docstring:
`message_conrent` -> `message_content`
<!--
~~## This is a **Code Change**~~
~~- [ ] I have tested my changes.~~
~~- [ ] I have updated the documentation to reflect the changes.~~
~~- [ ] I have run `task pyright` and fixed the relevant issues.~~

docs(automod): fix typo of intents.message_content

---

docs/api.rst
nextcord/enums.py

This PR adds the `InviteType` enum to the docs, to make the links referring to it clickable.

docs(enums): Add `InviteType` to the Enumerations section

---

nextcord/ui/modal.py
nextcord/webhook/async_.py

This PR makes webhooks respect the view.prevent_update value in a similar way as the other message sending or editing methods.

fix: check View.prevent_update in Webhook.send and Webhook.edit_message

---

nextcord/client.py

Refactors `Client.run()` to use modern methods of running the asyncio loop.
This MAY technically be a breaking change, as much of the weird/older school asyncio loop shenanigans have been removed?
I have tested the changes locally, but I'd like to see testing done on more wacky/custom setups to see if the technically breaking changes have any actual effect.

refactor: simplify Client.run()

---

nextcord/member.py

This fixes a bug where a user's display name in the bot's cache (`User.global_name`) would not update when the user changes their display name on Discord.

fix(User): apply new user global_name on user update

---

docs/api.rst
examples/application_commands/user_installed_command.py
nextcord/appinfo.py
nextcord/application_command.py
nextcord/client.py
nextcord/enums.py
nextcord/interactions.py
nextcord/message.py
nextcord/types/appinfo.py
nextcord/types/interactions.py
nextcord/types/message.py

This PR implements the "integration_types" and "contexts" fields on app commands to support User-Installed Apps. It also deprecates the "dm_permission" parameter in all application commands, as it has been replaced by "contexts".
The PR is marked as draft because user apps are still in preview.

feat(app-cmds): Implement User-Installed Apps

---

nextcord/webhook/async_.py
nextcord/webhook/sync.py

Nextcord doesn't currently allow editing webhook messages that were sent in threads. This aims to change that. I tested it preliminarily but it definitely needs more tests. Will sort it out soon. Most of it is copied straight from the implementation for sending webhook messages in threads.

feat(webhooks): allow editing webhook messages that were sent in threads

---

nextcord/state.py

This pull request adds a skip to the search for application subcommands for non chat_input commands, as subcommands are only intended for slash commands. This fixes context menu commands with spaces that were registering and unregistering with each bot startup.

fix(ConnectionState): Skip searching for subcommands if command type is not chat_input

---

nextcord/message.py

This PR adds a NotFound error in Message.edit
<!--

docs: missing NotFound error on Message.edit

---

nextcord/guild.py
nextcord/http.py

- Implements discord/discord-api-docs#7074
Tested with
```py
from nextcord import Intents, Interaction, Role
from nextcord.ext.commands import Bot
bot = Bot(
intents=Intents(guilds=True, message_content=True, messages=True),
default_guild_ids=[...],
)
@bot.slash_command()
async def role(inter: Interaction, role: Role):
assert inter.guild is not None
fetched_role = await inter.guild.fetch_role(role.id)
return await inter.send(repr(fetched_role))
bot.run(...)
```

feat(guild): add `fetch_role`

---

pyproject.toml

Reopening this because I borked my master on my fork. Sorry.
Audioop is a "dead battery" that has been removed by [PEP 594](https://peps.python.org/pep-0594/) in versions of Python >= 3.13.0. Thankfully, an LTS port has been created [here](https://github.com/AbstractUmbra/audioop). This PR would switch nextcord to audioop-lts for versions of Python that no longer include audioop OOTB.
Fixes #1174.
In terms of testing, I confirmed that, on Python 3.13., audioop-lts is installed; and on Python 3.12, nothing additional is installed.

build(player): migrate to audioop-lts on Python >= 3.13

---

.github/workflows/lint.yml
pyproject.toml

Add support for Python 3.13 to the version matrix in the lint job and the black target-version array.
Another PR towards #1222.

ci(lint): Add Python 3.13 to lint version matrix

---

pyproject.toml

Fixes https://github.com/nextcord/nextcord/issues/1220.
```
The HTML pages are in _build/html.
[I 241110 11:53:02 server:330] Serving on http://127.0.0.1:8069
[I 241110 11:53:02 handlers:62] Start watching changes
[I 241110 11:53:02 handlers:64] Start detecting changes
[I 241110 11:53:16 handlers:135] Browser Connected: http://localhost:8069/intro.html
```

chore: Upgrade Sphinx to 6.2.0 to allow building on Python 3.13

---

nextcord/ui/view.py

Introduced in #843 and discovered in [this help thread](https://discord.com/channels/881118111967883295/1310305439073828864), the new implementation for retrieving views via the client has duplicated views with multiple components.
This is due to removing the construction of a dictionary internally to make the list unqiue. This PR adds this method back and comments
it to ensure this isn't wrongly removed again.
With the following code, running `send_view` twice, and `all_views` once returns 4 views when it should be 2 unique, as seen in the new behaviour below.
```python
class MyView(View):
@button(label="one")
async def one(self, button, interaction: Interaction):
await interaction.response.send_message("one")
@button(label="two")
async def two(self, button, interaction: Interaction): …
```

fix(client): remove duplication of views in views/all_views

---

nextcord/asset.py
nextcord/member.py
nextcord/types/member.py

- Implements discord/discord-api-docs#6986
Tested with:
```py
from nextcord import Intents, Interaction, Member
from nextcord.ext.commands import Bot
bot = Bot(
intents=Intents(guilds=True, message_content=True, messages=True),
default_guild_ids=[...],
)
@bot.user_command()
async def user_banner(inter: Interaction, member: Member):
await inter.send(f"banner: {member.banner}")
await inter.followup.send(f"guild banner: {member.guild_banner}")
await inter.followup.send(f"display banner: {member.display_banner}")
bot.run(...)
```

feat(member): add guild banners

---

nextcord/utils.py

Adds a `integration_type` parameters to `utils.oauth_url`
Tested with:
```python
from nextcord.enums import IntegrationType
from nextcord.utils import oauth_url
print(oauth_url(919680394863984721, integration_type=IntegrationType.user_install))
```

feat(utils): add `integration_type` to `oauth_url` helper

---

nextcord/opus.py

Cherry picking this [patch](https://github.com/Rapptz/discord.py/pull/8052)
Apple Silicon has a special calling convention for variadic functions. This is an issue when using the Opus encoder:
```
Python 3.13.2 (main, Feb  4 2025, 14:51:09) [Clang 16.0.0 (clang-1600.0.26.6)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import nextcord.opus
>>> nextcord.opus.Encoder()
File "<python-input-1>", line 1, in <module>
nextcord.opus.Encoder()
~~~~~~~~~~~~~~~~~~~~~^^
File "/Users/ad/projects/nextcord/nextcord/opus.py", line 342, in __init__
self.set_bitrate(128)
~~~~~~~~~~~~~~~~^^^^^
File "/Users/ad/projects/nextcord/nextcord/opus.py", line 363, in set_bitrate
_lib.opus_encoder_ctl(self._state, CTL_SET_BITRATE, kbps * 1024) …
```

fix: specify correct types for Opus on Apple Silicon

---

nextcord/gateway.py

Occasionally discord will disconnect bots connected to a voice channel with code 1000 which will lead to an error.
"cherry picked" from https://github.com/Rapptz/discord.py/commit/ed615887f073e0dd74de0c43d56a65934582e903
NB: I wanted to properly cherry-pick the commit (to maintain git blame), but since the two repositories use different folders this was the best I could do.
<!--

fix(gateway): handle improper 1000 closures by Discord

---

nextcord/user.py

Before the new username system was implemented, the defaut_avatar index used depended on the discriminator. By introducing the new username system, discriminators were all set to "0", and the index is now dependent on the user ID, but users still on the old system would keep using the index provided by their discriminator. (see https://discord.com/developers/docs/reference#image-formatting-cdn-endpoints)
This behaviour wasn't implemented correctly in nextcord : the condition for checking if a user is using the new username system was done in reverse, resulting in differences from the official client.
This PR aims to fix that.

fix(user): use correct condition for default_avatar index

---

nextcord/components.py

This PR fixes a critical bug which causes bots to crash when receiving a message containing a select component with an option not having an emoji. The emoji variable was in that case not defined which caused an UnboundLocalError exception to be raised.

fix(components): prevent UnboundLocalError with missing emoji in SelectOptionPayload

---

nextcord/application_command.py
nextcord/interactions.py

This PR moves the functions used to resolve User, Message, and Role objects from functions in `application_command.py` to being private methods of `Interaction`.
This also fixes the "Cannot resolve members if Interaction.guild is None" error by resolving them as User objects instead.

refactor: move resolving funcs from app cmd file to Interaction
